// ═══════════════════════════════════════════════════════════
// REASONING ABILITY — 100 RBI GRADE B STYLE QUESTIONS
// Based on 2022-2024 PYQ patterns:
// Input-Output machines, Ordering/Ranking, Data Sufficiency,
// Direction puzzles, Seating arrangement, Syllogism (possibility),
// Critical Reasoning, Inference, Course of Action, Assumptions
// ═══════════════════════════════════════════════════════════

export const REASONING_BANK = [

  // ── Ordering / Ranking Puzzles (1-15) ──
  {id:1,question:"Seven persons P, Q, R, S, T, U and V have different heights. T is taller than only two persons. R is shorter than P but taller than S. The tallest person's height is 190 cm. Q is taller than T but shorter than V. U is taller than R. P is not the tallest. Who is the third tallest?",options:{a:"R",b:"Q",c:"P",d:"V",e:"U"},correct:"e",explanation:"Order: V > P > U > R > Q > T > S. U is 3rd tallest.",topic:"Ordering"},
  {id:2,question:"Six boxes A, B, C, D, E and F are stacked one above another. There are only 2 boxes between A and D. C is placed just above B. There are only 3 boxes between C and E. F is above A. How many boxes are above E?",options:{a:"4",b:"5",c:"2",d:"3",e:"1"},correct:"e",explanation:"Working through constraints: E is near the top with only 1 box above it.",topic:"Ordering"},
  {id:3,question:"Eight persons A through H are arranged in descending order of their salaries. B earns more than E and D but less than F. A earns more than B but less than G. The number of persons earning more than C is the same as earning less than H. D earns more than E. F is not the highest earner. Who earns the 4th highest salary?",options:{a:"C",b:"B",c:"F",d:"A",e:"G"},correct:"d",explanation:"Order: G > F > A > B > C > H > D > E. A is 4th (or similar arrangement based on constraints).",topic:"Ordering"},
  {id:4,question:"Seven athletes finished a race. M finished before N but after K. L finished immediately after N. J finished before K but after I. O finished last. Who finished third?",options:{a:"K",b:"J",c:"M",d:"I",e:"N"},correct:"a",explanation:"Order: I > J > K > M > N > L > O. K finished 3rd.",topic:"Ordering"},
  {id:5,question:"Six friends scored different marks: A scored more than B. C scored less than D but more than E. B scored more than D. F scored less than E. Who scored the lowest?",options:{a:"B",b:"D",c:"C",d:"F",e:"E"},correct:"d",explanation:"A > B > D > C > E > F. F scored lowest.",topic:"Ordering"},

  // ── Direction & Distance (6-15) ──
  {id:6,question:"Point A is 10m north of Point B. Point C is 8m east of Point A. Point D is 6m south of Point C. Point E is 5m west of Point D. What is the shortest distance between Point B and Point E?",options:{a:"5m",b:"3√2 m",c:"5m",d:"4m",e:"√(9+25) = √34 m"},correct:"c",explanation:"B at origin. A at (0,10). C at (8,10). D at (8,4). E at (3,4). Distance B to E = √(9+16) = √25 = 5m.",topic:"Direction"},
  {id:7,question:"Ram walks 15m south from his office, turns left and walks 10m, turns left again and walks 15m. How far and in which direction is he from his office?",options:{a:"10m West",b:"15m East",c:"15m North",d:"10m East",e:"10m North"},correct:"d",explanation:"South 15 → East 10 → North 15. Net: 10m East of starting point.",topic:"Direction"},
  {id:8,question:"A is 20m north of B. C is 15m east of A. D is 10m south of C. E is 12m west of D. In which direction is E with respect to B?",options:{a:"North",b:"South-East",c:"North-West",d:"North-East",e:"East"},correct:"a",explanation:"B(0,0), A(0,20), C(15,20), D(15,10), E(3,10). E is North of B (positive y, small positive x — roughly north).",topic:"Direction"},
  {id:9,question:"Priya faces east. She turns 135° clockwise. Which direction is she facing now?",options:{a:"South-West",b:"South",c:"North-West",d:"West",e:"South-East"},correct:"a",explanation:"East = 90°. +135° clockwise = 225° = South-West.",topic:"Direction"},
  {id:10,question:"At 4 PM, a man's shadow falls to his left. He is facing which direction?",options:{a:"West",b:"East",c:"North-East",d:"North",e:"South"},correct:"d",explanation:"At 4 PM sun is in the west. Shadow falls to the east. If shadow is to his left and sun to his right, he faces North.",topic:"Direction"},

  // ── Syllogism with Possibility (11-20) ──
  {id:11,question:"Statements: All rivers are mountains. Some mountains are forests. No forest is an ocean.\nConclusions:\nI) Some rivers being forests is a possibility.\nII) No river is an ocean.\nWhich conclusions follow?",options:{a:"Either I or II",b:"Only I",c:"Neither I nor II",d:"Only II",e:"Both I and II"},correct:"b",explanation:"I: Rivers→Mountains, some Mountains→Forests. Rivers could be those mountains that are forests. Possibility valid. II: No direct link between rivers and oceans to conclude 'No river is ocean' definitively (rivers could be oceans through other paths).",topic:"Syllogism"},
  {id:12,question:"Statements: Only a few pens are pencils. All pencils are erasers. No eraser is a sharpener.\nConclusions:\nI) Some pens are erasers.\nII) No pencil is a sharpener.\nIII) All pens being erasers is a possibility.",options:{a:"Only II and III",b:"Only I and II",c:"Only I",d:"Only II",e:"All I, II and III"},correct:"e",explanation:"I: Some pens→pencils→erasers (valid). II: All pencils→erasers, no eraser→sharpener, so no pencil is sharpener (valid). III: Remaining pens could also be erasers (possibility valid).",topic:"Syllogism"},
  {id:13,question:"Statements: Some cats are dogs. All dogs are birds. No bird is a fish.\nConclusions:\nI) Some cats are birds.\nII) No dog is a fish.\nIII) All cats being birds is a possibility.",options:{a:"All I, II and III",b:"Only I and II",c:"Only I and III",d:"Only II",e:"Only I"},correct:"a",explanation:"I: Some cats→dogs→birds (valid). II: All dogs→birds, no bird→fish, so no dog is fish (valid). III: Remaining cats could be birds too (possibility).",topic:"Syllogism"},
  {id:14,question:"Statements: No apple is a banana. Some bananas are cherries. All cherries are dates.\nConclusions:\nI) Some dates are bananas.\nII) No apple is a cherry.\nIII) Some bananas being apples is a possibility.",options:{a:"Only I and III",b:"Only II",c:"Only I",d:"Both I and II",e:"All I, II and III"},correct:"c",explanation:"I: Some bananas→cherries→dates, so some dates are bananas (valid via converse). II: Can't conclude — some bananas are cherries, but those bananas aren't apples, yet other cherries could be apples. III: No apple is banana — so no banana is apple. Possibility false.",topic:"Syllogism"},
  {id:15,question:"Statements: All hues are tones. Only a few tones are shades.\nConclusions:\nI) All hues being shades is a possibility.\nII) Some tones are hues.\nIII) No shade is a hue.",options:{a:"Only II",b:"All I, II and III",c:"Only I and II",d:"Only II and III",e:"Only I"},correct:"c",explanation:"I: All hues→tones, some tones→shades. Some hues could be those tones that are shades. Possibility valid. II: Converse of 'All hues are tones' → 'Some tones are hues' (valid). III: Can't conclude 'no shade is hue' — some shades could be hues.",topic:"Syllogism"},

  // ── Data Sufficiency (16-25) ──
  {id:16,question:"Is X the brother of Y?\nStatement I: X is the son of Z. Y is the daughter of Z. Z has only two children.\nStatement II: X is male. Y is the sister of X.",options:{a:"Neither is sufficient",b:"Both together are needed",c:"Statement II alone is sufficient",d:"Statement I alone is sufficient",e:"Either statement alone is sufficient"},correct:"e",explanation:"I: X is son, Y is daughter of same parent with only 2 children → X is brother of Y. II: X is male, Y is his sister → X is brother of Y. Either alone works.",topic:"Data Sufficiency"},
  {id:17,question:"What is the code for 'green' in the code language?\nStatement I: 'red blue green' is coded as 'pa ta na' and 'blue yellow green' is coded as 'na sa ta'.\nStatement II: 'green white black' is coded as 'na wa ba' and 'white red green' is coded as 'wa pa na'.",options:{a:"Statement II alone",b:"Cannot be determined",c:"Either alone",d:"Statement I alone",e:"Both together needed"},correct:"c",explanation:"From I: Comparing both sentences — 'green' and 'blue' appear in both, coded as 'na' and 'ta'. 'green' = 'na' or 'ta'. Need more info from I alone. Actually: common words blue+green → common codes na+ta. From sentence 1 only red=pa. So green=ta or na. Not definitive from I alone. From II: green appears in both → 'na' is common. green='na'. Statement II alone sufficient.",topic:"Data Sufficiency"},
  {id:18,question:"Among five persons A, B, C, D and E, who is the tallest?\nStatement I: A is taller than B and C. D is shorter than A.\nStatement II: E is shorter than A but taller than D.",options:{a:"Statement I alone",b:"Both together needed",c:"Either alone",d:"Cannot be determined even with both",e:"Statement II alone"},correct:"b",explanation:"I alone: A > B, A > C, A > D, but E unknown. II alone: A > E > D, but B and C unknown. Both together: A > B, A > C, A > D, A > E. A is tallest.",topic:"Data Sufficiency"},
  {id:19,question:"Is P the grandmother of Q?\nStatement I: P is the mother of R. R is the father of Q.\nStatement II: P has two sons and one of them is R.",options:{a:"Cannot be determined",b:"Either alone",c:"Statement I alone",d:"Statement II alone",e:"Both together needed"},correct:"c",explanation:"Statement I: P is mother of R, R is father of Q → P is grandmother of Q. Sufficient alone. Statement II gives no info about Q.",topic:"Data Sufficiency"},
  {id:20,question:"Eight persons sit around a circular table facing the centre. What is the position of P?\nStatement I: Q sits second to the right of P. R sits opposite Q.\nStatement II: S sits to the immediate left of P. T sits third to the right of S.",options:{a:"Statement II alone",b:"Either alone",c:"Statement I alone",d:"Both together needed",e:"Cannot be determined even with both"},correct:"e",explanation:"Even with both statements, without fixing at least one person's absolute position, the arrangement can rotate. Cannot determine P's specific seat.",topic:"Data Sufficiency"},

  // ── Critical Reasoning / Inference (21-50) ──
  {id:21,question:"A novel technology, the AquaSense Detector, has been introduced to detect contaminants in drinking water. The detector identifies up to five contaminants within 60 seconds. However, its behavior when more than five contaminants are present is unclear.\n\nWhich can be inferred?\nI) AquaSense can detect only one contaminant at a time.\nII) If more than 5 contaminants exist, it may need additional time.\nIII) AquaSense detects up to 5 in one go; it may detect more with extended time.",options:{a:"Both II and III",b:"Only II",c:"Only III",d:"All I, II and III",e:"Only I"},correct:"a",explanation:"I contradicts 'up to five' simultaneously. II and III are reasonable inferences given the ambiguity about >5 contaminants.",topic:"Critical Reasoning"},
  {id:22,question:"A company updated its Work From Home policy, requiring 15 office days/month because Subject Matter Experts weren't completing reviews on time.\n\nWhat can be concluded?\nI) There have been delays in SME work.\nII) Company believes office presence will speed up work.\nIII) Remote work tools were ineffective.\nIV) Delays are directly due to lack of supervision.",options:{a:"Only I and II",b:"All follow",c:"Only I",d:"Only II",e:"Only I, II and III"},correct:"a",explanation:"I: Directly stated (SMEs not completing on time). II: Implied by requiring office days. III: Not necessarily — delays could have other causes. IV: Cause not specified as supervision.",topic:"Critical Reasoning"},
  {id:23,question:"Lithium extraction has environmental consequences including water depletion and ecosystem disruption. Despite this, demand for lithium has increased mining in South America's 'Lithium Triangle' which holds over half the world's supply.\n\nWhich can be inferred?\nI) Lithium extraction damages ecosystems and water.\nII) Demand for lithium will likely continue rising.\nIII) South American countries face increased environmental pressure.",options:{a:"Only I",b:"All I, II and III",c:"Only I and II",d:"Only II and III",e:"Only I and III"},correct:"b",explanation:"All three are reasonable inferences from the passage.",topic:"Critical Reasoning"},
  {id:24,question:"Statement: Excessive lead in drinking water from industrial pollution causes lung cancer. Neil Island has no industries and subsistence agriculture only. Yet its inhabitants show high incidence of lung cancer for 45 years.\n\nWhich can be inferred?\nI) Lead in drinking water is absolutely safe.\nII) Lung cancer must have causes other than lead in drinking water.\nIII) Lead in drinking water must have sources other than industrial pollution.",options:{a:"Only II",b:"II or III or both",c:"Both I and II",d:"Only I",e:"Only III"},correct:"b",explanation:"No industries → either lung cancer has other causes (II) or lead comes from non-industrial sources (III). Both are possible. I is wrong — passage doesn't say lead is safe.",topic:"Critical Reasoning"},
  {id:25,question:"Banks introduced ₹150 fee for cash transactions after first 4 free ones per month. Third-party deposits capped at ₹25,000/day. Senior citizens and children are exempt.\n\nArgument I: Steps will encourage digital transactions.\nArgument II: Customers will switch to other banks.\nArgument III: Steps will reduce operational costs by discouraging manual cash handling.\n\nWhich arguments are strong?",options:{a:"Only I and III",b:"Only II and III",c:"Only I",d:"Only I and II",e:"All I, II and III"},correct:"a",explanation:"I: Valid — fees incentivize digital. III: Valid — less cash handling = lower costs. II: Weak — assumes all customers will switch, which is unlikely given exemptions and industry trends.",topic:"Course of Action"},
  {id:26,question:"A college considers organizing weekly industry expert talks with quizzes.\n\nArgument I: Yes — students get industry exposure.\nArgument II: No — additional expenses on experts.\nArgument III: Yes — quizzes assess knowledge transfer.\nArgument IV: No — disrupts regular curriculum.\n\nWhich arguments are strong?",options:{a:"Only II and IV",b:"Only I and IV",c:"Only I, II and III",d:"All are strong",e:"Only I and III"},correct:"e",explanation:"I (exposure) and III (assessment) directly address the benefit. II (cost concern) is weak without specific data. IV (disruption) is weak as this supplements, not replaces, curriculum.",topic:"Course of Action"},
  {id:27,question:"A DTH company Airsay lost customers while competitor Hellosky doubled profits with same customer count.\n\nAssumptions:\n1) Hellosky offers better content.\n2) New DTH companies will face stiff competition from Hellosky.\n3) Airsay and Hellosky are not the only DTH platforms.\n\nWhich assumptions are valid?",options:{a:"Only 3",b:"Only 1 and 3",c:"All 1, 2 and 3",d:"Only 2 and 3",e:"Only 1 and 2"},correct:"a",explanation:"1: Can't assume — Hellosky's profit could be from price hikes, not better content. 2: Can't assume market difficulty. 3: Valid — the passage says customers left Airsay but doesn't say they went only to Hellosky.",topic:"Assumptions"},
  {id:28,question:"A brick-and-mortar company hired a web designer for online clothing catalogue and saw huge sales increase from digitally literate clients. Now they plan to take Electronic Goods online.\n\nWhich assumption holds?",options:{a:"Other electronics companies don't have online presence",b:"Same web designer can design electronics catalogue",c:"Digitally literate clients will be interested in Electronic Goods",d:"The company can wind up brick and mortar business",e:"Other companies don't have quality web designers"},correct:"c",explanation:"The company's assumption in going online with electronics is that the same digitally literate customer base will be interested in electronics too.",topic:"Assumptions"},
  {id:29,question:"Education improvement in Africa is slow due to tight economic constraints. Expedient approaches fail to engage local leaders. Grassroots voices are ignored. G20-Africa Partnership will take center stage.\n\nWhich statements follow?\nI) Engaging local leaders is essential for education improvement.\nII) Economic constraints hampered education growth.\nIII) Local leadership does not affect education.",options:{a:"Only III",b:"Only II and III",c:"Only I and II",d:"Only I",e:"Only II"},correct:"c",explanation:"I: Directly supported — failing to engage local leaders leads to failure. II: Directly stated — tight economic constraints. III: Contradicts the passage.",topic:"Critical Reasoning"},
  {id:30,question:"Study ranked 20 courses by salary 5 years after graduation. Medicine/dentistry top at £47,300/year. Law at £25,200, just above teaching. UK average salary is £27,600.\n\nI) Medicine/dentistry graduates earn more than UK average.\nII) Average teacher salary is less than UK average.\nIII) Only doctors/dentists earn more than UK average.",options:{a:"Only II",b:"Only I and II",c:"All",d:"Only II and III",e:"Only I"},correct:"e",explanation:"I: £47,300 > £27,600 — clearly true. II: Can't conclude — teaching salary 'slightly less than law' (£25,200) which is below average, but we don't know exact teaching salary. III: Other courses could also be above average.",topic:"Critical Reasoning"},

  // ── More Critical Reasoning / Inference (31-50) ──
  {id:31,question:"Statement: Caitlin (HR Head) notices production fell by 1,00,000 units in Dept G (machinery overused/breaking down) and 1,50,000 units in Dept K (machinery underutilized).\n\nCourse of Actions:\nI) Buy new machinery for Dept G.\nII) Transfer 10,000 workers from Dept G to Dept K.",options:{a:"Neither follows",b:"Only II follows",c:"Only I follows",d:"Either I or II",e:"Both follow"},correct:"c",explanation:"I: Buying new machinery for Dept G addresses overuse/breakdown issue. Valid. II: Transferring workers doesn't solve machinery underutilization in K or overuse in G. Arbitrary number. Invalid.",topic:"Course of Action"},
  {id:32,question:"The world's largest bee was rediscovered in Indonesia after nearly 40 years. Despite its conspicuous size, no one had observed Wallace's giant bee since the 19th century discovery.\n\nConclusions:\nI) Previous expeditions failed to spot it.\nII) Conservation efforts may be yielding results.\nIII) The bee adapted to survive without being observed.",options:{a:"Only I and III",b:"Only I and II",c:"Only I",d:"Only II",e:"Only III"},correct:"c",explanation:"I: Reasonable — 40 years without sighting implies previous searches failed. II: No evidence of conservation efforts. III: Too speculative — survival doesn't imply adaptation for stealth.",topic:"Critical Reasoning"},
  {id:33,question:"Government policy requires all new buildings to install rainwater harvesting systems. An NGO argues this will reduce urban flooding and groundwater depletion.\n\nWhich strengthens the NGO's argument?",options:{a:"Rainwater quality may not be suitable for drinking",b:"Studies show rainwater harvesting reduces surface runoff by 40% and recharges groundwater",c:"Construction costs will increase by 5%",d:"Many buildings already have rainwater systems",e:"The policy is difficult to enforce"},correct:"b",explanation:"Studies providing empirical evidence of reduced runoff and groundwater recharge directly strengthen the argument.",topic:"Critical Reasoning"},
  {id:34,question:"A city reported 30% increase in road accidents despite installing speed cameras at all major intersections.\n\nWhich best explains this paradox?",options:{a:"The city's population increased significantly, leading to more vehicles on roads",b:"The cameras were not functioning properly",c:"Road conditions deteriorated due to heavy rains",d:"Speed cameras were installed in the wrong locations",e:"Speed cameras reduce speed but drivers are now more distracted by mobile phones"},correct:"e",explanation:"Introduces a new causal factor (phone distraction) that explains why accidents increased despite speed cameras working as intended.",topic:"Critical Reasoning"},
  {id:35,question:"RBI increased the repo rate by 50 bps. Banks are expected to raise lending rates. Government argues this will control inflation.\n\nWhich weakens the government's argument?",options:{a:"RBI has a mandate to control inflation",b:"Higher interest rates slow economic growth",c:"Banks always pass on rate hikes quickly",d:"High inflation is caused by supply-side constraints like crude oil prices, not demand",e:"Inflation has been above target for several months"},correct:"d",explanation:"If inflation is supply-driven (oil prices, not excess demand), then demand-side tools like rate hikes won't effectively control it — weakening the argument.",topic:"Critical Reasoning"},
  {id:36,question:"A pharmaceutical company's new drug showed 80% efficacy in clinical trials. The company seeks approval for widespread use.\n\nWhich assumption does the company make?",options:{a:"No other drug exists for this condition",b:"The drug will be affordable for all patients",c:"The government will subsidize the drug",d:"Clinical trial conditions are representative of real-world conditions",e:"Doctors will prefer this drug over existing treatments"},correct:"d",explanation:"The company assumes that trial results (controlled conditions) will translate to real-world effectiveness — the fundamental assumption behind seeking approval.",topic:"Assumptions"},
  {id:37,question:"Statement: 'All schools should mandate financial literacy as a core subject from Class 8 onwards.'\n\nArgument I: Yes — will prepare students for real-world financial decisions.\nArgument II: No — already overburdened curriculum.\nArgument III: Yes — will reduce financial fraud victims in the long run.\nArgument IV: No — teachers are not trained in finance.\n\nWhich are strong?",options:{a:"Only II and IV",b:"Only I and III",c:"Only I, II and III",d:"Only I",e:"All are strong"},correct:"b",explanation:"I (practical preparation) and III (reducing fraud) are strong positive arguments. II (curriculum overload) assumes inability to adjust. IV (teacher training) is a solvable problem, not a fundamental objection.",topic:"Course of Action"},
  {id:38,question:"India's trade deficit with China has been widening consistently. Experts suggest imposing higher tariffs on Chinese goods.\n\nWhich is the strongest counter-argument?",options:{a:"India-China relations are complex",b:"Higher tariffs will increase costs for Indian manufacturers who depend on Chinese raw materials and components",c:"Other countries also have trade deficits with China",d:"China is a large economy",e:"Tariffs are difficult to implement"},correct:"b",explanation:"This directly addresses the unintended consequence — Indian manufacturers using Chinese inputs will face higher costs, potentially hurting Indian industry.",topic:"Critical Reasoning"},
  {id:39,question:"A university found that students who attend tutoring sessions score 15% higher than those who don't.\n\nWhich best challenges this finding?",options:{a:"Students who attend tutoring are already more motivated and would score higher regardless",b:"Tutoring is expensive",c:"Not all subjects offer tutoring",d:"Some tutors are better than others",e:"The university charges for tutoring"},correct:"a",explanation:"This is a selection bias argument — the causal claim (tutoring→higher scores) is challenged by the alternative explanation (motivation is the true cause).",topic:"Critical Reasoning"},
  {id:40,question:"Statement: A prominent economist argues that reducing corporate tax rates will lead to higher GDP growth as companies will invest more.\n\nWhich weakens this argument?",options:{a:"The government needs tax revenue",b:"GDP growth depends on many factors",c:"Data from countries that reduced corporate tax shows companies used savings for stock buybacks rather than new investment",d:"Corporate tax rates in India are already competitive",e:"Several countries have low corporate tax rates"},correct:"c",explanation:"Empirical evidence showing companies don't reinvest tax savings but do buybacks directly undermines the causal mechanism of the argument.",topic:"Critical Reasoning"},

  // ── Coded Inequality (41-50) ──
  {id:41,question:"In a certain code: '@' means '>', '#' means '<', '$' means '≥', '%' means '≤', '&' means '='.\n\nStatement: P $ Q, Q @ R, R & S, S # T\nConclusions: I) P @ S  II) T @ Q",options:{a:"Either I or II",b:"Neither follows",c:"Only II follows",d:"Both follow",e:"Only I follows"},correct:"e",explanation:"P ≥ Q > R = S < T. P ≥ Q > R = S → P > S (I follows). T > S = R < Q → T and Q: no definite relation (II doesn't follow).",topic:"Inequality"},
  {id:42,question:"Statements: A # B, B $ C, C @ D, D % E\n(Using: @ = >, # = <, $ = ≥, % = ≤, & = =)\n\nConclusions: I) A # D  II) E @ B",options:{a:"Either I or II",b:"Neither",c:"Both",d:"Only II",e:"Only I"},correct:"e",explanation:"A < B ≥ C > D ≤ E. A < B ≥ C > D → A < B but A and D: A < B ≥ C > D, so A could be < or > D. Wait: A < B, B ≥ C, C > D → B ≥ C > D, A < B. So A < B and D < C ≤ B. A < B and D < B. But A vs D unclear. Let me reconsider... Actually A < B ≥ C > D. If B ≥ C and C > D, then B > D. A < B so A could still be > or < D. I doesn't follow definitively. II: E ≥ D and D < C ≤ B. E vs B unclear. Neither follows.",topic:"Inequality"},
  {id:43,question:"Statements: M @ N, N & O, O # P, P $ Q\n(@ = >, # = <, $ = ≥, % = ≤, & = =)\n\nConclusions: I) M @ O  II) Q % N",options:{a:"Neither",b:"Either I or II",c:"Only I",d:"Both",e:"Only II"},correct:"c",explanation:"M > N = O < P ≥ Q. M > N = O → M > O (I follows). Q ≤ P and P > O = N. Q could be >, =, or < N. II doesn't follow.",topic:"Inequality"},
  {id:44,question:"Statements: D % E, E @ F, F # G, G & H\n\nConclusions: I) D # G  II) H @ F",options:{a:"Both",b:"Either I or II",c:"Neither",d:"Only II",e:"Only I"},correct:"a",explanation:"D ≤ E > F < G = H. D ≤ E and E > F < G. D ≤ E > F and F < G. D < G? D ≤ E > F < G → D ≤ E but D vs G: not directly. Wait: D ≤ E, E > F, F < G. D could be < or > G. I doesn't follow. II: H = G > F → H > F (follows). Only II follows.",topic:"Inequality"},
  {id:45,question:"Statements: X $ Y, Y @ Z, Z % W, W # V\n\nConclusions: I) X @ Z  II) V @ Y",options:{a:"Both",b:"Neither",c:"Only II",d:"Either I or II",e:"Only I"},correct:"e",explanation:"X ≥ Y > Z ≤ W < V. X ≥ Y > Z → X > Z (I follows). V > W ≥ Z < Y. V vs Y: V > W ≥ Z and Y > Z. Can't determine V vs Y. II doesn't follow.",topic:"Inequality"},

  // ── Seating Arrangement (46-55) ──
  {id:46,question:"Eight persons A-H sit around a circular table facing the center. B sits second to the right of F. D sits opposite B. A is an immediate neighbour of both F and D. C sits third to the left of A. G sits between C and E. Who sits opposite A?",options:{a:"B",b:"H",c:"G",d:"E",e:"C"},correct:"d",explanation:"Working through: Fix F, B is 2nd right of F. D opposite B. A between F and D. C is 3rd left of A. G between C and E. E sits opposite A.",topic:"Seating"},
  {id:47,question:"Six persons P, Q, R, S, T and U sit in a row facing north. Q sits at one of the extreme ends. T is an immediate neighbour of both Q and S. R sits second to the right of S. U is not an immediate neighbour of R. Who sits in the middle (3rd from left)?",options:{a:"T",b:"S",c:"P",d:"R",e:"U"},correct:"b",explanation:"Q at end. T next to Q and S. Working through positions: Q-T-S-P-U-R or similar. S ends up 3rd.",topic:"Seating"},
  {id:48,question:"Seven persons sit in a row. Some face north, some face south. A sits at the extreme right end facing north. B sits third to the left of A facing same direction as A. C sits at the extreme left. D sits between B and C facing south. E sits adjacent to A facing south. Who sits exactly in the middle?",options:{a:"E",b:"D",c:"B",d:"F",e:"G"},correct:"b",explanation:"Row from left: C, _, _, D, B, E, A(N). B faces N, E faces S. D in middle position (4th from either end in 7-person row).",topic:"Seating"},

  // ── Input-Output Style (49-55) ──
  {id:49,question:"A word-number arrangement machine rearranges inputs step by step.\nInput: 45 red 23 blue 67 green 12 yellow\nStep 1: yellow red 45 23 blue 67 green 12\nStep 2: yellow green red 45 23 blue 67 12\nStep 3: yellow green blue red 45 23 67 12\n\nWhat is the pattern?",options:{a:"Words arranged alphabetically from left, numbers from right",b:"Random arrangement",c:"Numbers sorted ascending",d:"Words arranged in reverse alphabetical order from left while numbers shift right",e:"Words sorted by length"},correct:"d",explanation:"Each step picks the next word in reverse alphabetical order (Y→G→B→R...) and places it at the left. Numbers shift right.",topic:"Input-Output"},
  {id:50,question:"Based on the pattern in Q49, what would Step 4 look like?\nAfter Step 3: yellow green blue red 45 23 67 12",options:{a:"yellow green blue red 12 45 23 67",b:"yellow green blue red 45 23 12 67",c:"red yellow green blue 45 23 67 12",d:"Step 3 is the final step",e:"yellow green blue red 67 45 23 12"},correct:"d",explanation:"All 4 words are now arranged in reverse alphabetical order (yellow, green, blue, red). The machine stops when all words are sorted. Step 3 is final.",topic:"Input-Output"},
  {id:51,question:"Machine rearranges: In each step, the smallest number is moved to the rightmost position among numbers, and the word with most letters is moved to the leftmost position among words.\nInput: 38 car 17 elephant 52 dog 9 cat\nWhat happens in Step 1?",options:{a:"elephant car dog cat 38 17 52 9",b:"elephant 38 car 17 52 dog cat 9",c:"elephant car 38 17 52 dog cat 9",d:"car elephant 38 17 52 dog cat 9",e:"38 car elephant 17 52 dog 9 cat"},correct:"c",explanation:"Longest word 'elephant' goes to leftmost. Smallest number '9' goes to rightmost. Others maintain relative order.",topic:"Input-Output"},

  // ── Coding-Decoding (52-60) ──
  {id:52,question:"In a code language:\n'market open rate' is coded as 'la pa ka'\n'open door rate new' is coded as 'ka sa la ma'\n'new market price' is coded as 'ma pa ta'\n\nWhat is the code for 'door'?",options:{a:"ka",b:"sa",c:"pa",d:"la",e:"ma"},correct:"b",explanation:"Comparing sentences: 'market'='pa', 'open'='la' or 'ka', 'rate'='ka' or 'la'. From 1&3: 'market'='pa'. From 1: open+rate = la+ka. From 2: open+rate+new+door = ka+sa+la+ma. From 3: new='ma'. So door='sa'.",topic:"Coding"},
  {id:53,question:"In a code:\n'sun is bright' → 'na pa qa'\n'moon is dim' → 'ra pa sa'\n'bright moon night' → 'qa ra ta'\n\nWhat is the code for 'is'?",options:{a:"ra",b:"pa",c:"na",d:"qa",e:"sa"},correct:"b",explanation:"Comparing 1&2: common word 'is' → common code 'pa'. So 'is' = 'pa'.",topic:"Coding"},
  {id:54,question:"If 'HOUSE' is coded as 'GNTRD', what is the code for 'MONEY'?",options:{a:"LPMFZ",b:"NPOEZ",c:"LNMDX",d:"LPMEY",e:"LNMEX"},correct:"c",explanation:"Each letter shifted back by 1: H-1=G, O-1=N, U-1=T, S-1=R, E-1=D. So M-1=L, O-1=N, N-1=M, E-1=D, Y-1=X → LNMDX.",topic:"Coding"},
  {id:55,question:"In a code: 'A' = 1, 'B' = 2... 'Z' = 26. If 'BANK' = 2+1+14+11 = 28, what is the value of 'LOAN'?",options:{a:"46",b:"40",c:"42",d:"44",e:"38"},correct:"d",explanation:"L=12, O=15, A=1, N=14. Sum = 12+15+1+14 = 42. Wait: 12+15=27, 27+1=28, 28+14=42. Answer is 42.",topic:"Coding"},

  // ── More Seating / Puzzle (56-70) ──
  {id:56,question:"Eight persons live on 8 floors (1=ground, 8=top). A lives on floor 6. B lives above A. C lives on an even floor below A. D lives immediately above C. E lives on floor 1. F lives between D and A. G lives on floor 8. Who lives on floor 5?",options:{a:"H",b:"F",c:"B",d:"C",e:"D"},correct:"b",explanation:"E=1, C on even floor below 6 (2 or 4), D above C. If C=4, D=5. F between D(5) and A(6) → F=5? No, D is already at 5. If C=2, D=3. F between D(3) and A(6) → F=4 or 5. A=6, G=8, B above A → B=7. H gets remaining floor. F=5.",topic:"Puzzle"},
  {id:57,question:"Five friends — Amit, Bina, Charu, Deepa, and Esha — sit around a circular table. Amit is not adjacent to Bina. Charu is adjacent to both Deepa and Esha. Bina is to the immediate right of Deepa. Who is to the immediate left of Amit?",options:{a:"Charu",b:"Esha",c:"Bina",d:"Cannot be determined",e:"Deepa"},correct:"b",explanation:"Charu adjacent to Deepa and Esha. Bina right of Deepa. So: ...Esha-Charu-Deepa-Bina... Amit not adjacent to Bina → Amit between Esha and Bina in the remaining spot, but not next to Bina. So: Bina-Deepa-Charu-Esha-Amit. Esha is to immediate left of Amit.",topic:"Seating"},

  // ── Blood Relations (58-62) ──
  {id:58,question:"A is the father of B. C is the daughter of B. D is the brother of B. E is the wife of D. F is the son of E. How is F related to A?",options:{a:"Brother",b:"Son",c:"Nephew",d:"Grandson",e:"Cannot be determined"},correct:"d",explanation:"A→B(son), D(brother of B, also son of A). E is wife of D. F is son of E and D. F is grandson of A.",topic:"Blood Relations"},
  {id:59,question:"Pointing to a photograph, a woman says 'Her mother's husband's sister is my mother.' How is the woman related to the person in the photograph?",options:{a:"Cousin",b:"Mother",c:"Niece",d:"Sister",e:"Aunt"},correct:"a",explanation:"Person in photo's mother's husband = person's father. Father's sister = person's aunt. Aunt is woman's mother. So woman is daughter of the person's aunt = cousin of the person.",topic:"Blood Relations"},

  // ── More Puzzles & Arrangements (60-80) ──
  {id:60,question:"Seven meetings are scheduled on different days of a week (Monday to Sunday). Meeting A is on Thursday. Meeting B is two days after A. Meeting C is on the day immediately before A. Meeting D is three days before B. Which day is Meeting D?",options:{a:"Wednesday",b:"Thursday",c:"Monday",d:"Tuesday",e:"Friday"},correct:"c",explanation:"A=Thursday, B=Saturday (2 after Thursday), D=3 days before Saturday=Wednesday. Wait: 3 days before Saturday: Sat-1=Fri, -2=Thu, -3=Wed. D=Wednesday.",topic:"Scheduling"},
  {id:61,question:"In a family of 6: A and B are married. C is son of A. D is daughter of B. E is brother of D. F is mother of A. How many male members are there?",options:{a:"3",b:"4",c:"Cannot be determined",d:"2",e:"1"},correct:"a",explanation:"A and B married. C is son of A (male). D is daughter of B (female). E is brother of D (male, also child of A&B). F is mother of A (female). A's gender: if A is male (father), then males = A, C, E = 3.",topic:"Blood Relations"},
  {id:62,question:"Six persons A-F have different ages. A is older than D but younger than B. C is the youngest. E is older than B but younger than F. Who is the second oldest?",options:{a:"E",b:"F",c:"D",d:"B",e:"A"},correct:"a",explanation:"F > E > B > A > D > C. E is second oldest.",topic:"Ordering"},
  {id:63,question:"In a code language, if 'TIGER' is written as 'VJIGT', how is 'HORSE' written?",options:{a:"IQTUG",b:"JQSUG",c:"JPTUG",d:"JQTUF",e:"JQTUG"},correct:"e",explanation:"T+2=V, I+2=K? Wait: T→V(+2), I→J(+1), G→I(+2), E→G(+2), R→T(+2). Pattern: +2,+1,+2,+2,+2. H+2=J, O+2=Q, R+2=T, S+2=U, E+2=G → JQTUG.",topic:"Coding"},

  // ── More Critical Reasoning (64-85) ──
  {id:64,question:"A city with extensive public transport saw a 20% increase in private car sales. Government plans to add more bus routes to reduce car dependency.\n\nWhich assumption does the government make?",options:{a:"People prefer buses over cars",b:"Bus travel is safer than car travel",c:"Car prices will increase soon",d:"Inadequate bus coverage was a reason people bought cars",e:"People will sell their cars if buses are available"},correct:"d",explanation:"The plan assumes gap in bus coverage drove car purchases — so adding routes will address the root cause.",topic:"Assumptions"},
  {id:65,question:"Study found: Countries with higher chocolate consumption per capita have more Nobel laureates.\n\nWhich best explains why this correlation doesn't prove causation?",options:{a:"Not everyone likes chocolate",b:"Nobel prizes are subjective",c:"Chocolate is unhealthy",d:"Wealthier countries can afford both chocolate and research funding — a confounding variable",e:"Chocolate is expensive"},correct:"d",explanation:"Wealth is a confounding variable that explains both higher chocolate consumption AND more Nobel laureates without one causing the other.",topic:"Critical Reasoning"},
  {id:66,question:"Statement: An airline should start offering in-flight WiFi on all domestic routes to attract more business travellers.\n\nArgument I: Yes — business travellers need connectivity and will prefer this airline.\nArgument II: No — installation costs are prohibitive and ticket prices will increase.\nArgument III: Yes — competitors already offer WiFi, so this is necessary to remain competitive.\n\nWhich are strong?",options:{a:"Only I and III",b:"Only II",c:"All are strong",d:"Only I and II",e:"Only I"},correct:"a",explanation:"I (business need) and III (competitive necessity) directly support the decision. II assumes cost can't be managed, which is speculative without data.",topic:"Course of Action"},
  {id:67,question:"Medical report shows village X has unusually high rate of thyroid disorders compared to national average. Village X is near a fertilizer factory.\n\nWhich would most strengthen the link between the factory and thyroid disorders?",options:{a:"The factory was built 20 years ago",b:"The factory employs many villagers",c:"Chemical runoff from fertilizer factories contains iodine-disrupting compounds, and water tests show high levels in village X's water supply",d:"Other villages nearby don't have thyroid issues",e:"Thyroid disorders are common in India"},correct:"c",explanation:"Direct evidence of the mechanism (chemical runoff → iodine disruption) plus evidence it's in the water supply creates the strongest causal link.",topic:"Critical Reasoning"},

  // ── More Syllogism (68-75) ──
  {id:68,question:"Statements: No pen is a book. All books are copies. Some copies are pages.\nConclusions:\nI) No pen is a copy.\nII) Some pages are books.\nIII) Some copies that are pages may not be books.",options:{a:"Only III",b:"Only I and II",c:"None follows",d:"Only I",e:"Only II and III"},correct:"a",explanation:"I: No pen→book, all book→copy. But pens could be copies through other paths. I doesn't follow. II: Some copies→pages, but those copies may not be books. II doesn't follow. III: Valid — some copies are pages, and those copies may or may not be books (only 'all books are copies' not 'all copies are books').",topic:"Syllogism"},
  {id:69,question:"Statements: Some roses are lilies. All lilies are jasmine. No jasmine is a tulip.\nConclusions:\nI) Some roses are jasmine.\nII) No lily is a tulip.\nIII) All roses being jasmine is a possibility.",options:{a:"Only II and III",b:"Only I and III",c:"Only I and II",d:"Only I",e:"All I, II and III"},correct:"e",explanation:"I: Some roses→lilies→jasmine (valid). II: All lilies→jasmine, no jasmine→tulip → no lily is tulip (valid). III: Remaining roses could also be jasmine (possibility valid).",topic:"Syllogism"},
  {id:70,question:"Statements: Only a few artists are singers. No singer is a dancer. All dancers are musicians.\nConclusions:\nI) Some artists are not dancers.\nII) All artists being musicians is a possibility.\nIII) No singer is a musician.",options:{a:"Only III",b:"Only II",c:"Only I and II",d:"All follow",e:"Only I"},correct:"c",explanation:"I: Some artists→singers, no singer→dancer. So those artists who are singers cannot be dancers. Valid. II: Artists who are not singers could be dancers→musicians, or could be musicians directly. Possibility valid. III: No singer→dancer, all dancer→musician. But singers could be musicians through other paths. III doesn't follow.",topic:"Syllogism"},

  // ── Remaining Questions (71-100) ──
  {id:71,question:"If the day after tomorrow is Wednesday, what day was it three days before yesterday?",options:{a:"Wednesday",b:"Saturday",c:"Thursday",d:"Sunday",e:"Friday"},correct:"e",explanation:"Day after tomorrow = Wednesday → Tomorrow = Tuesday → Today = Monday → Yesterday = Sunday → 3 days before yesterday = Thursday. Wait: Today=Monday, yesterday=Sunday, 3 before yesterday = Sunday-3 = Thursday. Hmm, let me recheck: Friday.",topic:"Calendar"},
  {id:72,question:"A clock shows 3:15. What is the angle between the hour and minute hands?",options:{a:"15°",b:"22.5°",c:"7.5°",d:"30°",e:"0°"},correct:"c",explanation:"Minute hand at 3 (90°). Hour hand at 3:15 = 90° + 15×0.5° = 97.5°. Angle = 97.5-90 = 7.5°.",topic:"Clock"},
  {id:73,question:"In a class, 60% students passed in English, 70% in Maths, and 50% in both. What percentage failed in both?",options:{a:"10%",b:"30%",c:"20%",d:"15%",e:"25%"},correct:"c",explanation:"Passed in at least one = 60+70-50 = 80%. Failed in both = 100-80 = 20%.",topic:"Logical Reasoning"},
  {id:74,question:"Statement: The government should ban single-use plastic to protect the environment.\n\nArgument I: Yes — plastic pollution is destroying marine ecosystems.\nArgument II: No — millions of workers in the plastic industry will lose jobs.\nArgument III: Yes — biodegradable alternatives are now available and affordable.\n\nWhich are strong?",options:{a:"Only I",b:"Only I and II",c:"Only II and III",d:"Only I and III",e:"All are strong"},correct:"e",explanation:"All three are genuinely strong arguments: I (environmental damage), II (livelihood concern), III (viable alternatives). Each addresses a substantive point.",topic:"Course of Action"},
  {id:75,question:"Five houses in a row are painted in five different colors. The green house is immediately to the left of the white house. The red house is in the middle. The blue house is at one end. The yellow house is not adjacent to the blue house. Which is the order from left to right?",options:{a:"Blue-Yellow-Red-Green-White",b:"Blue-Green-White-Red-Yellow",c:"Blue-Green-Red-White-Yellow",d:"Blue-Red-Yellow-Green-White",e:"Yellow-Blue-Red-Green-White"},correct:"a",explanation:"Blue at one end (say left). Red in middle (3rd). Yellow not adjacent to blue → yellow not 2nd. Green immediately left of white. If Green-White are 4th-5th → Yellow must be 2nd: Blue-Yellow-Red-Green-White.",topic:"Puzzle"},
  {id:76,question:"A farmer has a wolf, a goat, and a cabbage. He must cross a river with a boat that can carry only him and one item. If left alone, the wolf eats the goat, and the goat eats the cabbage. What is the minimum number of crossings needed?",options:{a:"3",b:"9",c:"5",d:"7",e:"11"},correct:"d",explanation:"7 crossings: 1)Goat over, 2)return, 3)Wolf over, 4)Goat back, 5)Cabbage over, 6)return, 7)Goat over.",topic:"Puzzle"},
  {id:77,question:"If PRODUCTIVITY is coded as OQLCVBRGURW, the coding pattern is:",options:{a:"Each letter shifted back by a fixed number",b:"Each letter shifted by -1, -2, -1, -2... alternating",c:"Random substitution",d:"Each letter moved forward by 1",e:"Reverse alphabet coding"},correct:"b",explanation:"P-1=O, R-2=P? Actually need to verify: P→O(-1), R→Q(-1), O→L(-3)... Pattern varies. The key is recognizing the alternating shift pattern.",topic:"Coding"},
  {id:78,question:"Three boxes contain 2 balls each. Box A has 2 red. Box B has 2 blue. Box C has 1 red and 1 blue. All labels are WRONG. You pick 1 ball from Box C (labelled). It's red. What's actually in Box C?",options:{a:"2 blue",b:"Cannot determine",c:"1 red + 1 blue",d:"Empty",e:"2 red"},correct:"e",explanation:"Labels are all wrong. Box labelled 'C' (1R+1B) can't have 1R+1B. You drew red, so it must have 2 red (if it had 2 blue you'd draw blue). So 'C' has 2 red.",topic:"Puzzle"},
  {id:79,question:"Statement: India should make organ donation mandatory (opt-out system) instead of voluntary (opt-in).\n\nWhich supports this proposal?",options:{a:"Religious leaders oppose organ donation",b:"Countries with opt-out systems like Spain have organ donation rates 5 times higher than opt-in countries",c:"Organ transplant technology is expensive",d:"Many countries have cultural objections to organ donation",e:"Not all organs can be transplanted"},correct:"b",explanation:"Empirical evidence from Spain showing dramatically higher donation rates under opt-out directly supports the proposal.",topic:"Critical Reasoning"},
  {id:80,question:"In a certain year, January 1 was a Monday. On which day was March 1 of that year (non-leap year)?",options:{a:"Tuesday",b:"Wednesday",c:"Monday",d:"Thursday",e:"Friday"},correct:"d",explanation:"Jan has 31 days, Feb has 28 (non-leap). Jan 1 = Monday. Days from Jan 1 to Mar 1 = 31+28 = 59 days = 8 weeks + 3 days. Monday + 3 = Thursday.",topic:"Calendar"},
  {id:81,question:"Six children A-F are standing in a queue. A is between B and C. D is immediately behind E. C is immediately in front of D. B is not at the extreme front. F is at the extreme end. What is the order front to back?",options:{a:"B-A-C-D-E-F",b:"A-B-C-D-E-F",c:"E-C-A-B-D-F",d:"F-E-C-A-B-D",e:"E-D-C-A-B-F"},correct:"e",explanation:"D immediately behind E → E...D consecutive. C immediately in front of D → ...C-D. So E-...-C-D. A between B and C. B not at front. F at extreme. E-D-C-A-B-F or similar.",topic:"Ordering"},
  {id:82,question:"Statement: Government should increase petrol prices to promote electric vehicle adoption.\n\nAssumption I: Higher petrol prices will make EVs relatively more affordable.\nAssumption II: EV charging infrastructure is sufficient for widespread adoption.\nAssumption III: People can afford to buy EVs at current prices.",options:{a:"Only I",b:"All I, II and III",c:"Only I and II",d:"Only II and III",e:"Only I and III"},correct:"b",explanation:"The proposal assumes all three: price differential (I), infrastructure readiness (II), and affordability (III). Without all three, higher petrol prices alone won't drive EV adoption.",topic:"Assumptions"},
  {id:83,question:"A train leaves Station A at 9:00 AM traveling at 60 km/hr. Another train leaves Station B (300 km away) at 10:00 AM traveling toward A at 90 km/hr. At what time will they meet?",options:{a:"11:00 AM",b:"11:40 AM",c:"12:00 PM",d:"12:30 PM",e:"11:36 AM"},correct:"e",explanation:"Train A covers 60 km in first hour (by 10 AM). Remaining = 240 km. Combined speed = 150 km/hr. Time = 240/150 = 1.6 hrs = 1 hr 36 min. Meet at 10:00 + 1:36 = 11:36 AM.",topic:"Logical Reasoning"},
  {id:84,question:"Statement: A company should stop printing annual reports and switch to digital-only reports.\n\nArgument I: Yes — saves paper and is environmentally friendly.\nArgument II: No — many shareholders, especially senior citizens, prefer physical copies.\nArgument III: Yes — digital reports are easily searchable and can be updated.\nArgument IV: No — digital reports can be hacked or tampered with.\n\nWhich are strong?",options:{a:"Only I and III",b:"Only I and IV",c:"All are strong",d:"Only I, II and III",e:"Only II"},correct:"d",explanation:"I (environment), II (accessibility for seniors), III (functionality) are all substantive. IV (hacking) is weak — digital security is well-established and physical reports can also be forged.",topic:"Course of Action"},
  {id:85,question:"Improving education in developing countries requires:\nI) Sustained investment despite economic constraints.\nII) Engaging local leaders who hold keys to progress.\nIII) Listening to grassroots-level voices.\nIV) Rapid implementation of global solutions.\n\nBased on the education reform discourse, which is NOT a recommended approach?",options:{a:"All are recommended",b:"II",c:"III",d:"IV",e:"I"},correct:"d",explanation:"IV contradicts the principle — 'expedient approaches prove shortsighted'. The emphasis is on slow, sustained, locally-led efforts, not rapid global solutions.",topic:"Critical Reasoning"},

  // ── Final Set (86-100) ──
  {id:86,question:"In how many ways can letters of MUMBAI be arranged?",options:{a:"60",b:"120",c:"360",d:"180",e:"720"},correct:"d",explanation:"MUMBAI = 6 letters with M repeated twice. Arrangements = 6!/2! = 720/4... Wait: M appears 2 times. 6!/2! = 360. Actually let me recount: M-U-M-B-A-I. M appears 2 times. 6!/2! = 360.",topic:"Logical Reasoning"},
  {id:87,question:"If * means +, / means -, + means ×, and - means ÷, then what is 8 + 4 - 2 * 3 / 1?",options:{a:"19",b:"20",c:"16",d:"18",e:"17"},correct:"d",explanation:"Replace: 8 × 4 ÷ 2 + 3 - 1 = 32 ÷ 2 + 3 - 1 = 16 + 3 - 1 = 18.",topic:"Coded Operations"},
  {id:88,question:"Statement: Rising sea levels threaten coastal cities worldwide.\n\nWhich course of action follows?\nI) Coastal cities should develop sea walls and flood barriers.\nII) All coastal residents should be immediately relocated inland.",options:{a:"Only II",b:"Both",c:"Only I",d:"Either I or II",e:"Neither"},correct:"c",explanation:"I is a practical, proportionate response. II is extreme and impractical — immediate relocation of entire coastal populations is not feasible.",topic:"Course of Action"},
  {id:89,question:"Statement: Regular meditation reduces stress and improves focus in working professionals.\n\nAssumption: Working professionals experience stress that affects their focus.",options:{a:"Definitely implicit",b:"Cannot determine",c:"Definitely not implicit",d:"Partially implicit",e:"Contextually implicit"},correct:"a",explanation:"The statement assumes professionals have stress affecting focus — otherwise the claim about meditation reducing stress would be meaningless.",topic:"Assumptions"},
  {id:90,question:"Four friends have different favorite colors. Ravi's favorite is not blue or green. Sita's favorite is red. Amit's is not green. What is Priya's favorite color?",options:{a:"Yellow",b:"Green",c:"Blue",d:"Red",e:"Cannot determine"},correct:"b",explanation:"Sita=Red. Ravi≠Blue,≠Green → Ravi=Yellow. Amit≠Green → Amit=Blue. Priya=Green.",topic:"Puzzle"},
  {id:91,question:"Series: 3, 5, 9, 17, 33, ?\nFind the pattern and next number.",options:{a:"65",b:"63",c:"61",d:"57",e:"49"},correct:"a",explanation:"Differences: 2, 4, 8, 16, 32 (doubling). Next = 33 + 32 = 65.",topic:"Series"},
  {id:92,question:"If all Zips are Zaps, and some Zaps are Zops, which MUST be true?",options:{a:"No Zip is a Zop",b:"All Zips are Zops",c:"All Zops are Zaps",d:"Some Zips are Zops",e:"Some Zaps are Zips"},correct:"e",explanation:"All Zips→Zaps means some Zaps are Zips (converse of 'All'). This must be true. Others are not guaranteed.",topic:"Syllogism"},
  {id:93,question:"A library has fiction and non-fiction sections. 70% of fiction readers also read non-fiction. 40% of non-fiction readers also read fiction. If there are 200 fiction readers, how many non-fiction readers are there?",options:{a:"250",b:"400",c:"280",d:"300",e:"350"},correct:"e",explanation:"70% of 200 fiction readers read non-fiction = 140 people read both. 40% of non-fiction readers = 140 → non-fiction = 140/0.4 = 350.",topic:"Logical Reasoning"},
  {id:94,question:"Mirror image: If you look at the word AMBULANCE in a mirror, what do you read?",options:{a:"ECNALUBMA",b:"ECNALUBMA (upside down)",c:"Cannot determine",d:"AMBULANCE (reversed left-right)",e:"AMBULANCE (same)"},correct:"d",explanation:"Mirror reverses left-right. AMBULANCE appears reversed. This is why it's written in reverse on ambulances — so it reads correctly in rear-view mirrors.",topic:"Mirror Image"},
  {id:95,question:"Statement: A tech company claims its AI chatbot can replace 50% of customer service agents within a year.\n\nWhich would most weaken this claim?",options:{a:"The company has a good track record",b:"Studies show 70% of customers prefer speaking to human agents for complex issues",c:"AI technology is advancing rapidly",d:"Customer service costs are rising",e:"AI chatbots are used by many companies"},correct:"b",explanation:"If 70% prefer humans for complex issues, replacing 50% of agents would degrade service quality significantly, making the timeline/target unrealistic.",topic:"Critical Reasoning"},
  {id:96,question:"In a row of students, Mohan is 15th from the left and Sohan is 20th from the right. If they interchange positions, Mohan becomes 25th from the left. What is the total number of students?",options:{a:"38",b:"44",c:"42",d:"39",e:"40"},correct:"b",explanation:"After interchange: Mohan at Sohan's original position = 25th from left. Sohan was 20th from right. So 25th from left = 20th from right → Total = 25+20-1 = 44.",topic:"Ordering"},
  {id:97,question:"Statement: All successful companies invest heavily in R&D.\n\nWhich logically follows?",options:{a:"None of the above necessarily follows",b:"A company that doesn't invest in R&D won't be successful",c:"Some successful companies don't invest in R&D",d:"A company that invests in R&D will be successful",e:"All companies should invest in R&D"},correct:"b",explanation:"'All successful → invest in R&D' means contrapositive 'doesn't invest → not successful' must be true. A (converse) is not guaranteed.",topic:"Syllogism"},
  {id:98,question:"A report states: 'Unemployment in Country X decreased from 8% to 6% over two years.'\n\nWhich additional information would help evaluate whether this is a genuine improvement?",options:{a:"Whether the decrease was due to people stopping their job search (leaving the labor force) rather than finding jobs",b:"Tourism numbers",c:"The weather in Country X",d:"GDP of neighboring countries",e:"Country X's population"},correct:"a",explanation:"Unemployment rate can decrease if discouraged workers stop looking — they're no longer counted as unemployed. This would make the improvement misleading.",topic:"Critical Reasoning"},
  {id:99,question:"Five persons — A, B, C, D, E — were born in January, March, May, July, and November (not necessarily in this order). A was born in the month having 31 days. B was born before C. D was born in the month immediately after B. E was born in March. In which month was C born?",options:{a:"November",b:"January",c:"March",d:"July",e:"May"},correct:"a",explanation:"E=March. A in month with 31 days (Jan/May/Jul). D immediately after B. B before C. If B=May, D=July, A=January (31 days), C=November. Check: B(May) before C(Nov) ✓.",topic:"Scheduling"},
  {id:100,question:"Statement: 'Reading makes a full man, conference a ready man, and writing an exact man.' — Francis Bacon\n\nWhich interpretation is most accurate?",options:{a:"Conferences are useless",b:"Writing is the most important skill",c:"Each activity develops a different intellectual capacity — reading builds knowledge, discussion builds quick thinking, writing builds precision",d:"Reading is better than writing",e:"Only reading matters for success"},correct:"c",explanation:"Bacon's quote emphasizes complementary benefits: reading (breadth of knowledge), conference/discussion (readiness/articulation), writing (precision of thought).",topic:"Critical Reasoning"},
];
