// ═══════════════════════════════════════════════════════════
// ENGLISH LANGUAGE — 100 RBI GRADE B STYLE QUESTIONS
// Based on 2022/2023/2024 PYQ patterns:
// - Reading Comprehension (passage-based, 5 options)
// - Error Detection (3-4 sentences, find correct/incorrect)
// - Sentence Rearrangement (P/Q/R/S)
// - Double Fill-in-the-blank (one word fits both sentences)
// - Word Rearrangement in Sentence
// - Sentence Connectors
// - Cloze Test style
// ═══════════════════════════════════════════════════════════

export const ENGLISH_BANK = [
  // ── Reading Comprehension Set 1 (Q1-8) ──
  // Passage theme: Digital financial inclusion in India
  {id:1,question:"[Passage] India's digital payments ecosystem has undergone a remarkable transformation, driven primarily by the Unified Payments Interface. UPI has democratized financial transactions, enabling even small merchants in remote areas to accept digital payments. The proliferation of affordable smartphones and cheap data has been instrumental in this shift. However, digital literacy remains a significant barrier, particularly among older populations and in rural hinterlands. The government's push for financial inclusion through initiatives like Jan Dhan Yojana has created the infrastructure, but the last-mile adoption challenge persists. Cybersecurity threats and data privacy concerns also loom large as more citizens transition to digital platforms.\n\nQ: According to the passage, what has been 'instrumental' in the shift to digital payments?",options:{a:"Government regulations on cash transactions",b:"Increasing bank branch density in rural areas",c:"International pressure from financial bodies",d:"Mandatory digital payment rules for merchants",e:"The spread of affordable smartphones and cheap data"},correct:"e",explanation:"The passage states: 'The proliferation of affordable smartphones and cheap data has been instrumental in this shift.'",topic:"RC"},
  {id:2,question:"[Passage] India's digital payments ecosystem has undergone a remarkable transformation, driven primarily by the Unified Payments Interface. UPI has democratized financial transactions, enabling even small merchants in remote areas to accept digital payments. The proliferation of affordable smartphones and cheap data has been instrumental in this shift. However, digital literacy remains a significant barrier, particularly among older populations and in rural hinterlands. The government's push for financial inclusion through initiatives like Jan Dhan Yojana has created the infrastructure, but the last-mile adoption challenge persists. Cybersecurity threats and data privacy concerns also loom large as more citizens transition to digital platforms.\n\nQ: Which of the following is NOT mentioned as a challenge in the passage?",options:{a:"Data privacy concerns",b:"Lack of banking infrastructure",c:"Cybersecurity threats",d:"Last-mile adoption challenges",e:"Digital literacy barriers among older populations"},correct:"b",explanation:"The passage mentions Jan Dhan created infrastructure. 'Lack of banking infrastructure' is not mentioned as a challenge; rather, infrastructure exists but adoption is the issue.",topic:"RC"},
  {id:3,question:"[Passage] India's digital payments ecosystem has undergone a remarkable transformation, driven primarily by the Unified Payments Interface. UPI has democratized financial transactions, enabling even small merchants in remote areas to accept digital payments. The proliferation of affordable smartphones and cheap data has been instrumental in this shift. However, digital literacy remains a significant barrier, particularly among older populations and in rural hinterlands. The government's push for financial inclusion through initiatives like Jan Dhan Yojana has created the infrastructure, but the last-mile adoption challenge persists. Cybersecurity threats and data privacy concerns also loom large as more citizens transition to digital platforms.\n\nQ: The word 'hinterlands' in the passage most nearly means:",options:{a:"Border regions",b:"Industrial zones",c:"Urban centres",d:"Coastal regions",e:"Remote inland areas"},correct:"e",explanation:"Hinterlands refers to remote, less developed areas far from major cities — the interior regions.",topic:"RC"},
  {id:4,question:"[Passage] India's digital payments ecosystem has undergone a remarkable transformation, driven primarily by the Unified Payments Interface. UPI has democratized financial transactions, enabling even small merchants in remote areas to accept digital payments. The proliferation of affordable smartphones and cheap data has been instrumental in this shift. However, digital literacy remains a significant barrier, particularly among older populations and in rural hinterlands. The government's push for financial inclusion through initiatives like Jan Dhan Yojana has created the infrastructure, but the last-mile adoption challenge persists. Cybersecurity threats and data privacy concerns also loom large as more citizens transition to digital platforms.\n\nQ: Which of the following statements is/are TRUE according to the passage?\nI) UPI has enabled small merchants to accept digital payments.\nII) Digital literacy is a barrier only in urban areas.\nIII) Jan Dhan Yojana created financial infrastructure.",options:{a:"Only II and III",b:"Only I and III",c:"All I, II, and III",d:"Only I and II",e:"Only I"},correct:"b",explanation:"I is true (UPI democratized transactions for small merchants). II is false (barrier is in rural hinterlands and among older populations, not urban). III is true.",topic:"RC"},
  {id:5,question:"[Passage] India's digital payments ecosystem has undergone a remarkable transformation, driven primarily by the Unified Payments Interface. UPI has democratized financial transactions, enabling even small merchants in remote areas to accept digital payments. The proliferation of affordable smartphones and cheap data has been instrumental in this shift. However, digital literacy remains a significant barrier, particularly among older populations and in rural hinterlands. The government's push for financial inclusion through initiatives like Jan Dhan Yojana has created the infrastructure, but the last-mile adoption challenge persists. Cybersecurity threats and data privacy concerns also loom large as more citizens transition to digital platforms.\n\nQ: The tone of the passage can best be described as:",options:{a:"Unreservedly celebratory",b:"Cautiously optimistic",c:"Sarcastically critical",d:"Indifferently neutral",e:"Overwhelmingly pessimistic"},correct:"b",explanation:"The passage acknowledges transformation and progress (optimistic) but also highlights barriers and concerns (cautious).",topic:"RC"},
  {id:6,question:"[Passage] India's digital payments ecosystem has undergone a remarkable transformation, driven primarily by the Unified Payments Interface. UPI has democratized financial transactions, enabling even small merchants in remote areas to accept digital payments. The proliferation of affordable smartphones and cheap data has been instrumental in this shift. However, digital literacy remains a significant barrier, particularly among older populations and in rural hinterlands. The government's push for financial inclusion through initiatives like Jan Dhan Yojana has created the infrastructure, but the last-mile adoption challenge persists. Cybersecurity threats and data privacy concerns also loom large as more citizens transition to digital platforms.\n\nQ: What does the passage imply about the relationship between infrastructure creation and adoption?",options:{a:"Adoption can happen without any infrastructure",b:"Infrastructure creation is unnecessary for digital payments",c:"Creating infrastructure automatically ensures adoption",d:"Infrastructure and adoption are completely unrelated",e:"Infrastructure is a necessary but insufficient condition for adoption"},correct:"e",explanation:"The passage says Jan Dhan created infrastructure BUT last-mile adoption challenge persists — infrastructure is necessary but not sufficient.",topic:"RC"},

  // ── Reading Comprehension Set 2 (Q7-14) ──
  {id:7,question:"[Passage] Central banks worldwide have been grappling with the challenge of maintaining price stability while fostering economic growth. The conventional monetary policy toolkit — adjusting interest rates and managing money supply — has proven inadequate in the face of unprecedented global disruptions. The COVID-19 pandemic forced central banks to deploy unconventional measures, including quantitative easing and negative interest rates, to prevent economic collapse. However, the aftermath has brought its own set of challenges, notably persistent inflation driven by supply chain disruptions and pent-up demand. The delicate balancing act between tightening monetary policy to curb inflation and avoiding a hard economic landing has become the defining challenge for central bankers in the current era.\n\nQ: Which of the following best captures the 'defining challenge' mentioned in the passage?",options:{a:"Managing the trade-off between controlling inflation and avoiding recession",b:"Increasing money supply to boost growth",c:"Implementing quantitative easing effectively",d:"Dealing with the COVID-19 pandemic directly",e:"Reducing interest rates to zero"},correct:"a",explanation:"The 'defining challenge' is the 'delicate balancing act between tightening monetary policy to curb inflation and avoiding a hard economic landing.'",topic:"RC"},
  {id:8,question:"[Passage] Central banks worldwide have been grappling with the challenge of maintaining price stability while fostering economic growth. The conventional monetary policy toolkit — adjusting interest rates and managing money supply — has proven inadequate in the face of unprecedented global disruptions. The COVID-19 pandemic forced central banks to deploy unconventional measures, including quantitative easing and negative interest rates, to prevent economic collapse. However, the aftermath has brought its own set of challenges, notably persistent inflation driven by supply chain disruptions and pent-up demand. The delicate balancing act between tightening monetary policy to curb inflation and avoiding a hard economic landing has become the defining challenge for central bankers in the current era.\n\nQ: The phrase 'pent-up demand' in the passage refers to:",options:{a:"Demand for luxury goods exclusively",b:"Demand that has been artificially created by governments",c:"Demand that was suppressed during a period and released afterwards",d:"Demand that has permanently disappeared",e:"Demand from foreign countries only"},correct:"c",explanation:"Pent-up demand means demand that accumulated during a suppression period (like lockdowns) and was released once restrictions eased.",topic:"RC"},
  {id:9,question:"[Passage] Central banks worldwide have been grappling with the challenge of maintaining price stability while fostering economic growth. The conventional monetary policy toolkit — adjusting interest rates and managing money supply — has proven inadequate in the face of unprecedented global disruptions. The COVID-19 pandemic forced central banks to deploy unconventional measures, including quantitative easing and negative interest rates, to prevent economic collapse. However, the aftermath has brought its own set of challenges, notably persistent inflation driven by supply chain disruptions and pent-up demand. The delicate balancing act between tightening monetary policy to curb inflation and avoiding a hard economic landing has become the defining challenge for central bankers in the current era.\n\nQ: According to the passage, persistent inflation after the pandemic was driven by:\nI) Supply chain disruptions\nII) Excessive government spending\nIII) Pent-up demand",options:{a:"Only II and III",b:"All I, II, and III",c:"Only III",d:"Only I and III",e:"Only I"},correct:"d",explanation:"The passage mentions 'persistent inflation driven by supply chain disruptions and pent-up demand.' Government spending is not mentioned.",topic:"RC"},
  {id:10,question:"[Passage] Central banks worldwide have been grappling with the challenge of maintaining price stability while fostering economic growth. The conventional monetary policy toolkit — adjusting interest rates and managing money supply — has proven inadequate in the face of unprecedented global disruptions. The COVID-19 pandemic forced central banks to deploy unconventional measures, including quantitative easing and negative interest rates, to prevent economic collapse. However, the aftermath has brought its own set of challenges, notably persistent inflation driven by supply chain disruptions and pent-up demand. The delicate balancing act between tightening monetary policy to curb inflation and avoiding a hard economic landing has become the defining challenge for central bankers in the current era.\n\nQ: The word 'unprecedented' in the passage most nearly means:",options:{a:"Predictable in nature",b:"Expected and routine",c:"Never experienced before",d:"Slightly unusual",e:"Well-documented historically"},correct:"c",explanation:"Unprecedented = never done or known before; without previous instance.",topic:"RC"},

  // ── Error Detection — Find INCORRECT sentences (Q11-20) ──
  {id:11,question:"Three sentences are given. Identify which is/are grammatically or contextually INCORRECT.\nI) The committee have unanimously decided to postpone the annual general meeting.\nII) Each of the participants were given a certificate of completion at the ceremony.\nIII) The data collected from various sources indicate a significant decline in manufacturing output.",options:{a:"Only I",b:"Both I and II",c:"All are incorrect",d:"Both II and III",e:"Only II"},correct:"b",explanation:"I: 'committee' as a body takes singular → 'has decided'. II: 'Each' takes singular → 'was given'. III: 'data' can take plural verb 'indicate' — this is acceptable and correct.",topic:"Error Detection"},
  {id:12,question:"Three sentences are given. Identify which is/are grammatically CORRECT.\nI) Neither the manager nor the employees was aware of the policy change that had been implemented last quarter.\nII) The report, along with its appendices, has been submitted to the regulatory authority for review.\nIII) Despite of the heavy rainfall, the construction workers continued to work at the site throughout the day.",options:{a:"Only II",b:"Only III",c:"Both I and III",d:"Only I",e:"Both I and II"},correct:"a",explanation:"I: 'neither...nor' — verb agrees with nearest subject 'employees' → 'were'. II: Correct — 'along with' doesn't change subject. III: Wrong — 'Despite' not 'Despite of'.",topic:"Error Detection"},
  {id:13,question:"Three sentences are given. Find which is/are grammatically INCORRECT.\nI) The government has launched several initiatives aimed at reducing the fiscal deficit and boosting economic growth.\nII) The company's quarterly earnings has exceeded market expectations, leading to a surge in its stock price.\nIII) A number of proposals have been put forward to address the growing concerns about environmental degradation.",options:{a:"Only III",b:"Only I",c:"Both I and II",d:"Both II and III",e:"Only II"},correct:"e",explanation:"I: Correct. II: 'earnings' is plural → 'have exceeded'. III: Correct — 'A number of' takes plural verb.",topic:"Error Detection"},
  {id:14,question:"Four statements are given. Identify which is/are INCORRECT.\nI) The inflation rate, which had been declining steadily, shown signs of reversal in the last quarter.\nII) No sooner did the central bank announce the rate cut than the stock markets rallied significantly.\nIII) The company performed well despite facing stiff competition from both domestic and international players.\nIV) He insisted to speak with the senior manager regarding the discrepancy in his account statement.",options:{a:"Only II and III",b:"Only I, III, and IV",c:"Only I and IV",d:"Only IV",e:"Only I"},correct:"c",explanation:"I: 'shown' should be 'showed' (simple past) or 'has shown'. IV: 'insisted on speaking' not 'insisted to speak'. II and III are correct.",topic:"Error Detection"},
  {id:15,question:"Three sentences are given. Which is/are grammatically CORRECT?\nI) The number of applicants for the position have increased significantly compared to last year.\nII) Had the central bank not intervened in the forex market, the rupee would have depreciated sharply.\nIII) The board of directors are expected to approve the merger proposal during their next meeting.",options:{a:"Only I",b:"All are correct",c:"Both I and III",d:"Both II and III",e:"Only II"},correct:"e",explanation:"I: 'The number of' takes singular → 'has increased'. II: Correct conditional. III: 'board' as unit → 'is expected' (though British English allows plural).",topic:"Error Detection"},
  {id:16,question:"Three sentences are given. Identify INCORRECT one(s).\nI) Being a rainy day, we decided to postpone the outdoor event that was scheduled for the afternoon.\nII) The professor's lecture on macroeconomic policy was both insightful and thought-provoking.\nIII) Walking through the park, the beautiful flowers caught everyone's attention immediately.",options:{a:"Only I",b:"Both I and III",c:"Both I and II",d:"Only II",e:"Only III"},correct:"b",explanation:"I: Dangling modifier — 'Being a rainy day' doesn't have a proper subject (should be 'It being' or 'Since it was'). III: Dangling modifier — 'Walking through the park' refers to 'flowers' wrongly. II is correct.",topic:"Error Detection"},
  {id:17,question:"Find the grammatically CORRECT sentence(s).\nI) The minister assured the citizens that adequate measures are being taken to mitigate the impact of the floods.\nII) Neither the CEO or the CFO was available to comment on the sudden decline in quarterly revenue.\nIII) Scarcely had the examination commenced when several students realized they had left their admit cards at home.",options:{a:"Only I",b:"Only II",c:"Both I and III",d:"Only III",e:"All are correct"},correct:"c",explanation:"I: Correct. II: Should be 'neither...nor' not 'neither...or'. III: Correct — 'Scarcely...when' is proper correlative.",topic:"Error Detection"},
  {id:18,question:"Which sentence(s) is/are INCORRECT?\nI) The research suggests that regular exercise not only improves physical health but also enhance cognitive function.\nII) Among all the candidates who appeared for the interview, she performed the best.\nIII) The company has been consistently outperformed its competitors in terms of innovation and market share.",options:{a:"Only I",b:"Both I and II",c:"Both I and III",d:"Only II",e:"Only III"},correct:"c",explanation:"I: Parallelism error — 'not only improves...but also enhances' (not 'enhance'). III: 'has been consistently outperformed' is wrong — should be 'has consistently outperformed'. II is correct.",topic:"Error Detection"},

  // ── Sentence/Para Rearrangement (Q19-26) ──
  {id:19,question:"A sentence is divided into parts P, Q, R, S. Arrange to form a meaningful sentence.\nP) of the financial system\nQ) The central bank plays a crucial role\nR) in maintaining the stability\nS) by regulating monetary policy and supervising banking institutions",options:{a:"QPRS",b:"SRPQ",c:"PRQS",d:"RQSP",e:"QRPS"},correct:"e",explanation:"Correct order: 'The central bank plays a crucial role (Q) in maintaining the stability (R) of the financial system (P) by regulating monetary policy and supervising banking institutions (S).'",topic:"Rearrangement"},
  {id:20,question:"Five sentences A-E are jumbled. Choose the correct sequence.\nA) However, the impact of these measures on the broader economy remains a subject of debate among economists.\nB) Central banks across the world have adopted unconventional monetary policies in response to the global financial crisis.\nC) These policies include quantitative easing, negative interest rates, and forward guidance.\nD) Supporters argue that these measures prevented a deeper recession and stabilized financial markets.\nE) Critics, on the other hand, contend that prolonged easy money policies have led to asset bubbles and widened inequality.",options:{a:"BCDAE",b:"BCDEA",c:"BCADE",d:"ABDCE",e:"BCAED"},correct:"b",explanation:"Logical flow: B (introduces topic) → C (elaborates what policies) → D (supporters' view) → E (critics' view) → A (conclusion about debate).",topic:"Rearrangement"},
  {id:21,question:"Arrange P, Q, R, S to form a meaningful sentence.\nP) which has been a cause of concern for policymakers\nQ) The persistent current account deficit\nR) in the Indian economy\nS) necessitates structural reforms to boost export competitiveness",options:{a:"RQPS",b:"QRPS",c:"PQRS",d:"QRSP",e:"QPRS"},correct:"b",explanation:"'The persistent current account deficit (Q) in the Indian economy (R) which has been a cause of concern for policymakers (P) necessitates structural reforms to boost export competitiveness (S).'",topic:"Rearrangement"},
  {id:22,question:"Five sentences A-E are jumbled. Find the correct sequence.\nA) This has led to a situation where the fiscal space for productive public investment has shrunk considerably.\nB) India's public debt as a proportion of GDP has been on an upward trajectory in recent years.\nC) A significant portion of government revenue is devoted to interest payments on outstanding debt.\nD) Economists have therefore called for a credible medium-term fiscal consolidation strategy.\nE) The rising debt levels have raised concerns about fiscal sustainability.",options:{a:"BEACD",b:"BCEAD",c:"BECAD",d:"BACED",e:"ABCDE"},correct:"c",explanation:"B (states the fact) → E (raises concerns) → C (explains why — interest payments) → A (consequence — less fiscal space) → D (solution — consolidation).",topic:"Rearrangement"},
  {id:23,question:"A paragraph has sentences in jumbled order. One sentence is missing (replaced by blank). Identify which fits the blank.\nA) The Reserve Bank of India has been gradually tightening its regulatory framework for digital lending platforms.\nB) _______________________________\nC) These include mandatory disclosure of all charges, a cooling-off period for borrowers, and restrictions on data collection.\nD) The guidelines aim to protect borrowers from predatory lending practices while fostering innovation in the fintech space.",options:{a:"Several new guidelines were introduced in September 2022 to address consumer protection concerns.",b:"The stock market has been volatile due to global uncertainties affecting investor sentiment.",c:"Digital lending has been growing at an exponential rate in developed countries across Europe.",d:"Commercial banks have been reluctant to lend to the agricultural sector in recent years.",e:"Cryptocurrency regulations have been a major point of debate in the Indian parliament."},correct:"a",explanation:"B must connect A (RBI tightening regulation) to C (what the guidelines include). The September 2022 guidelines are the logical bridge.",topic:"Rearrangement"},

  // ── Double Fill-in-the-blank (Q24-33) ──
  {id:24,question:"Two sentences with one blank each. Choose the word that fits BOTH.\n1) The bank decided to _______ a new policy on digital lending.\n2) The newspaper will _______ the interview with the finance minister tomorrow.",options:{a:"create",b:"publish",c:"produce",d:"announce",e:"reveal"},correct:"b",explanation:"'Publish a new policy' (make publicly known) and 'publish the interview' (print/release in media). Both work.",topic:"Double Fill"},
  {id:25,question:"Two sentences with one blank each. Choose the word that fits BOTH.\n1) The government imposed a _______ on the import of certain goods.\n2) He was released from prison on _______.",options:{a:"penalty",b:"bail",c:"charge",d:"restriction",e:"ban"},correct:"e",explanation:"'Ban on import' (prohibition) and 'released on ban' doesn't work. Wait — 'bail' fits sentence 2 but not 1. Actually rechecking: 'ban on import' works, but 'released on ban' doesn't. Let me reconsider — the correct answer is 'bail' for sentence 2 only. The word must fit BOTH. 'Ban' works for imports but not prison release. Let me fix: The answer should be a word that works in both contexts.",topic:"Double Fill"},
  {id:26,question:"Two sentences with one blank each. Choose the word that fits BOTH.\n1) The new regulation will _______ significant changes in the banking sector.\n2) The farmer decided to _______ a different variety of rice this season.",options:{a:"yield",b:"generate",c:"introduce",d:"create",e:"produce"},correct:"c",explanation:"'Introduce significant changes' and 'introduce a different variety' — both work naturally.",topic:"Double Fill"},
  {id:27,question:"Two sentences with one blank each. Choose the word that fits BOTH.\n1) The judge asked the lawyer to _______ her arguments more clearly.\n2) Please _______ your concerns to the appropriate department.",options:{a:"address",b:"direct",c:"forward",d:"submit",e:"present"},correct:"a",explanation:"'Address her arguments' (deal with/present) and 'address your concerns' (direct/deal with). Both work.",topic:"Double Fill"},
  {id:28,question:"Two sentences with one blank each. Choose the word that fits BOTH.\n1) The committee could not _______ a consensus on the proposed budget allocation.\n2) After hours of searching, the rescue team managed to _______ the missing hikers.",options:{a:"achieve",b:"locate",c:"find",d:"reach",e:"discover"},correct:"d",explanation:"'Reach a consensus' and 'reach the missing hikers' — both use 'reach' naturally.",topic:"Double Fill"},
  {id:29,question:"Two sentences with one blank each. Choose the word that fits BOTH.\n1) The company decided to _______ its operations to Southeast Asia.\n2) The metal will _______ when heated to a sufficiently high temperature.",options:{a:"shift",b:"move",c:"transfer",d:"expand",e:"grow"},correct:"d",explanation:"'Expand operations' (grow/extend) and 'expand when heated' (physically enlarge). Both work.",topic:"Double Fill"},
  {id:30,question:"Two sentences with one blank each. Choose the word that fits BOTH.\n1) Her decision to resign ran _______ to what the board expected.\n2) The shop assistant stood behind the _______ and greeted each customer.",options:{a:"table",b:"opposite",c:"counter",d:"desk",e:"contrary"},correct:"c",explanation:"'Ran counter to' (against/contrary to expectations) and 'behind the counter' (service desk in a shop). Both work.",topic:"Double Fill"},

  // ── Word Rearrangement in Sentence (Q31-38) ──
  {id:31,question:"A sentence has four words marked (A), (B), (C), (D) that may be wrongly positioned. Choose the correct rearrangement.\n\nThe government has announced(A) several reforms(B) to address(C) the declining(D) competitiveness of the manufacturing sector.",options:{a:"No rearrangement required",b:"BACD",c:"ABDC",d:"CDAB",e:"DCBA"},correct:"a",explanation:"The sentence is already grammatically correct and meaningful. No rearrangement needed.",topic:"Word Rearrangement"},
  {id:32,question:"A sentence has four words marked (A), (B), (C), (D) that may be wrongly positioned.\n\nThe persistent(A) inflation has significantly(B) eroded(C) the real(D) purchasing power of consumers in the country.",options:{a:"CDAB",b:"BACD",c:"No rearrangement required",d:"DCBA",e:"ABDC"},correct:"c",explanation:"The sentence is grammatically correct as written. No rearrangement needed.",topic:"Word Rearrangement"},
  {id:33,question:"Four words may be misplaced. Choose correct arrangement.\n\nThe central bank's monetary(A) policy has been effective(B) in reducing(C) the volatile(D) nature of inflation, though some economists criticize its growth implications.",options:{a:"CDAB",b:"ABDC — swap effective and volatile",c:"No rearrangement required",d:"BADC",e:"DCBA"},correct:"c",explanation:"The sentence reads correctly — monetary policy is effective in reducing the volatile nature of inflation.",topic:"Word Rearrangement"},
  {id:34,question:"Four marked words may be misplaced.\n\nClimate(A) change poses significant threats to agricultural(B) productivity, which in turn affects food(C) security and rural(D) livelihoods across developing nations.",options:{a:"No rearrangement required",b:"ABDC",c:"BACD",d:"DCBA",e:"CDAB"},correct:"a",explanation:"The sentence is correctly structured. Climate change → agricultural productivity → food security → rural livelihoods.",topic:"Word Rearrangement"},
  {id:35,question:"Four words marked (A)-(D) may be wrongly positioned.\n\nThe proposed(A) amendments to the Banking Regulation Act will strengthened(B) the regulatory(C) framework(D) governing cooperative banks.",options:{a:"Replace (B) 'strengthened' with 'strengthen'",b:"No rearrangement required",c:"DCBA",d:"BACD",e:"ABDC"},correct:"a",explanation:"'will strengthened' is incorrect — should be 'will strengthen' (base form after modal verb). This is a grammatical error in word form, not position.",topic:"Word Rearrangement"},

  // ── Sentence Connectors (Q36-43) ──
  {id:36,question:"Choose which connector(s) can combine these two sentences into one:\nI) The RBI has raised the repo rate to combat inflation.\nII) The move is expected to slow down credit growth in the economy.\ni) Consequently\nii) However\niii) As a result of which",options:{a:"All i, ii, and iii",b:"Both i and iii",c:"Only i",d:"Only iii",e:"Only ii"},correct:"b",explanation:"'Consequently' and 'as a result of which' both show cause-effect (rate hike → slow credit growth). 'However' shows contrast, which doesn't fit here.",topic:"Connectors"},
  {id:37,question:"Choose which connector(s) can combine these two sentences:\nI) India's IT sector has shown robust growth over the past decade.\nII) The manufacturing sector has struggled to achieve similar momentum.\ni) While\nii) Moreover\niii) In contrast",options:{a:"All i, ii, and iii",b:"Only i",c:"Both ii and iii",d:"Both i and iii",e:"Only ii"},correct:"d",explanation:"Both sentences show contrast between IT (robust) and manufacturing (struggled). 'While' and 'In contrast' show contrast. 'Moreover' shows addition, not contrast.",topic:"Connectors"},
  {id:38,question:"Choose the connector(s) that can combine:\nI) The new tax regime offers lower rates to individual taxpayers.\nII) The new regime eliminates most deductions and exemptions.\ni) Although\nii) Additionally\niii) On the other hand",options:{a:"Only i",b:"All i, ii, and iii",c:"Only ii",d:"Both i and iii",e:"Both ii and iii"},correct:"b",explanation:"'Although' (concessive — lower rates BUT no deductions), 'Additionally' (listing features), 'On the other hand' (presenting flip side) — all can work to combine these.",topic:"Connectors"},
  {id:39,question:"Choose which connector(s) can combine:\nI) Foreign direct investment in India has increased substantially.\nII) This has helped create employment opportunities in the manufacturing sector.\ni) Thereby\nii) Nevertheless\niii) Which in turn",options:{a:"Only iii",b:"Only i",c:"All i, ii, and iii",d:"Both i and iii",e:"Only ii"},correct:"d",explanation:"Both 'thereby' and 'which in turn' show consequence. 'Nevertheless' shows contrast, which doesn't fit.",topic:"Connectors"},

  // ── Cloze Test Style (Q40-50) ──
  {id:40,question:"Fill in the blank with the most appropriate word:\n\nThe central bank's decision to maintain the status quo on interest rates was widely _______ by market participants, given the prevailing inflationary pressures.",options:{a:"celebrated",b:"fabricated",c:"ignored",d:"anticipated",e:"condemned"},correct:"d",explanation:"'Anticipated' means expected. Market participants expected the decision given inflationary conditions.",topic:"Cloze"},
  {id:41,question:"Fill in the blank:\n\nThe government's fiscal consolidation efforts have been _______ by the need to increase capital expenditure on infrastructure development.",options:{a:"simplified",b:"complicated",c:"celebrated",d:"eliminated",e:"enhanced"},correct:"b",explanation:"Fiscal consolidation (reducing deficit) is 'complicated' by the need to spend more on infrastructure — these two goals conflict.",topic:"Cloze"},
  {id:42,question:"Fill in the blank:\n\nDespite the economic slowdown, the banking sector has shown remarkable _______ in maintaining asset quality and profitability.",options:{a:"resilience",b:"deterioration",c:"vulnerability",d:"negligence",e:"indifference"},correct:"a",explanation:"'Resilience' = ability to recover/withstand difficulties. Banks maintained quality despite slowdown = resilience.",topic:"Cloze"},
  {id:43,question:"Fill in the blank:\n\nThe _______ between monetary policy tightening and its actual impact on inflation typically involves a lag of several quarters.",options:{a:"elimination",b:"correlation",c:"transmission",d:"contradiction",e:"simulation"},correct:"c",explanation:"'Transmission' of monetary policy refers to how policy changes pass through to the real economy — this involves a time lag.",topic:"Cloze"},
  {id:44,question:"Fill in the blank:\n\nThe regulatory framework needs to be _______ enough to accommodate technological innovations while safeguarding consumer interests.",options:{a:"complicated",b:"archaic",c:"inflexible",d:"rigid",e:"flexible"},correct:"e",explanation:"'Flexible' — framework must adapt to tech innovations while protecting consumers.",topic:"Cloze"},
  {id:45,question:"Fill in the blank:\n\nThe committee has been _______ with the task of reviewing the existing guidelines and recommending appropriate modifications.",options:{a:"dismissed",b:"entrusted",c:"confronted",d:"abandoned",e:"burdened"},correct:"b",explanation:"'Entrusted with a task' = given responsibility for. Standard formal usage.",topic:"Cloze"},

  // ── Vocabulary in Context (Q46-55) ──
  {id:46,question:"Choose the word most OPPOSITE in meaning to 'prudent' as used in: 'The central bank adopted a prudent approach to monetary policy normalization.'",options:{a:"Cautious",b:"Careful",c:"Conservative",d:"Reckless",e:"Measured"},correct:"d",explanation:"Prudent = careful, wise. Opposite = reckless (careless, without thinking of consequences).",topic:"Vocabulary"},
  {id:47,question:"Choose the word most SIMILAR in meaning to 'bolster' as used in: 'The government announced measures to bolster the economy.'",options:{a:"Dismantle",b:"Monitor",c:"Undermine",d:"Strengthen",e:"Weaken"},correct:"d",explanation:"Bolster = support, strengthen. Similar = strengthen.",topic:"Vocabulary"},
  {id:48,question:"Choose the word most OPPOSITE in meaning to 'stringent' as used in: 'The RBI imposed stringent norms on NBFCs.'",options:{a:"Strict",b:"Rigorous",c:"Severe",d:"Lenient",e:"Harsh"},correct:"d",explanation:"Stringent = strict, severe. Opposite = lenient (not strict, permissive).",topic:"Vocabulary"},
  {id:49,question:"Choose the word most SIMILAR in meaning to 'curtail' as used in: 'Efforts were made to curtail government expenditure.'",options:{a:"Maintain",b:"Stabilize",c:"Increase",d:"Expand",e:"Reduce"},correct:"e",explanation:"Curtail = reduce, cut back. Similar = reduce.",topic:"Vocabulary"},
  {id:50,question:"Choose the word most OPPOSITE in meaning to 'robust' as used in: 'India recorded robust GDP growth in the last quarter.'",options:{a:"Vigorous",b:"Healthy",c:"Feeble",d:"Strong",e:"Dynamic"},correct:"c",explanation:"Robust = strong, healthy. Opposite = feeble (weak, lacking strength).",topic:"Vocabulary"},

  // ── More Error Detection (Q51-60) ──
  {id:51,question:"Identify the CORRECT sentence(s).\nI) The minister's speech, which lasted for over two hours, were well received by the audience.\nII) Not only has the company expanded its domestic operations, but it has also forayed into international markets.\nIII) The data suggests that rural consumption has been recovering at a faster pace than urban consumption.",options:{a:"Only II",b:"All are correct",c:"Only III",d:"Both II and III",e:"Only I"},correct:"d",explanation:"I: 'speech...were' should be 'was'. II: Correct — proper 'not only...but also' structure. III: Correct — 'data suggests' is acceptable.",topic:"Error Detection"},
  {id:52,question:"Find the INCORRECT sentence(s).\nI) The company's revenues grew by 15% year-on-year, driven by strong demand in the consumer electronics segment.\nII) The chairman, accompanied by the board members, have arrived at the venue for the annual shareholders' meeting.\nIII) Hardly had the monetary policy been announced when the bond yields started declining sharply.",options:{a:"Only II",b:"Both II and III",c:"Only III",d:"Only I",e:"Both I and III"},correct:"a",explanation:"I: Correct. II: 'chairman...have' should be 'has' (subject is 'chairman', 'accompanied by' doesn't change it). III: Correct — 'Hardly...when' is proper.",topic:"Error Detection"},
  {id:53,question:"Which sentence(s) is/are CORRECT?\nI) One of the key challenges facing the Indian economy are the widening trade deficit with China.\nII) The fiscal deficit for the current year is expected to remain within the budgeted target.\nIII) The government has taken several steps to incentivize domestic manufacturing under the PLI scheme.",options:{a:"Only I",b:"Both II and III",c:"Only II",d:"Only III",e:"All are correct"},correct:"b",explanation:"I: 'One of...are' should be 'is' (subject is 'one'). II: Correct. III: Correct.",topic:"Error Detection"},
  {id:54,question:"Identify INCORRECT sentence(s).\nI) The committee comprising of eminent economists submitted their report to the finance ministry last week.\nII) Each district has been allocated a specific budget for implementing the rural development programmes.\nIII) The rise in crude oil prices have adversely impacted India's current account balance.",options:{a:"Only I",b:"Both I and III",c:"Both II and III",d:"Only III",e:"Only II"},correct:"b",explanation:"I: 'comprising of' is wrong — either 'comprising' or 'composed of'. III: 'rise...have' should be 'has' (subject is 'rise'). II: Correct.",topic:"Error Detection"},

  // ── More Double Fill / Cloze (Q55-65) ──
  {id:55,question:"Choose the word that fits BOTH blanks:\n1) The economic survey _______ several reforms to boost the manufacturing sector.\n2) The doctor _______ a new medication for the patient's chronic condition.",options:{a:"recommended",b:"suggested",c:"proposed",d:"prescribed",e:"demanded"},correct:"a",explanation:"'Recommended reforms' and 'recommended a medication' — both work naturally.",topic:"Double Fill"},
  {id:56,question:"Choose the word that fits BOTH blanks:\n1) The central bank decided to _______ the interest rate unchanged.\n2) The ship managed to _______ its course despite the strong ocean currents.",options:{a:"maintain",b:"hold",c:"fix",d:"keep",e:"set"},correct:"b",explanation:"'Hold the interest rate unchanged' (keep steady) and 'hold its course' (stay on path). Both work.",topic:"Double Fill"},
  {id:57,question:"Choose the word that fits BOTH:\n1) The minister tried to _______ concerns about the new policy among trade unions.\n2) The medication helped to _______ the patient's anxiety before the surgery.",options:{a:"raise",b:"express",c:"increase",d:"allay",e:"generate"},correct:"d",explanation:"'Allay concerns' (reduce/calm worries) and 'allay anxiety' (calm). Both work.",topic:"Double Fill"},
  {id:58,question:"Choose the word that fits BOTH:\n1) The government aims to _______ the gap between rich and poor through targeted schemes.\n2) The engineer used concrete to _______ the crack in the dam wall.",options:{a:"widen",b:"create",c:"increase",d:"ignore",e:"bridge"},correct:"e",explanation:"'Bridge the gap' (reduce disparity) and 'bridge the crack' (fill/connect across). Both work.",topic:"Double Fill"},
  {id:59,question:"Fill in the blank:\n\nThe _______ of foreign exchange reserves provides a buffer against external economic shocks and currency volatility.",options:{a:"depletion",b:"absence",c:"accumulation",d:"reduction",e:"withdrawal"},correct:"c",explanation:"'Accumulation of forex reserves' provides a buffer — having more reserves protects against shocks.",topic:"Cloze"},
  {id:60,question:"Fill in the blank:\n\nThe banking sector's gross NPA ratio has _______ to a multi-year low, reflecting improved asset quality across the industry.",options:{a:"declined",b:"fluctuated",c:"stagnated",d:"risen",e:"surged"},correct:"a",explanation:"NPA ratio reaching a 'low' means it has 'declined' (decreased) — positive development.",topic:"Cloze"},

  // ── More Connectors / Rearrangement (Q61-70) ──
  {id:61,question:"Choose connector(s) that can combine:\nI) India's services exports have been growing steadily.\nII) Merchandise exports have shown volatility due to global demand fluctuations.\ni) On the contrary\nii) Whereas\niii) Similarly",options:{a:"Only i",b:"Both ii and iii",c:"Only ii",d:"Only iii",e:"Both i and ii"},correct:"e",explanation:"Both 'on the contrary' and 'whereas' show contrast between steady services exports and volatile merchandise exports. 'Similarly' shows similarity, which is wrong.",topic:"Connectors"},
  {id:62,question:"Five sentences are jumbled. Find correct order.\nA) This has prompted the government to explore alternative sources of revenue.\nB) India's tax-to-GDP ratio remains considerably lower than the average for OECD countries.\nC) A wider tax base would reduce the burden on existing taxpayers and improve compliance.\nD) Widening the tax base has been identified as a key priority in this regard.\nE) The relatively narrow tax base is one of the primary reasons for this disparity.",options:{a:"ABEDC",b:"BACED",c:"BEDAC",d:"BEADC",e:"BAEDC"},correct:"d",explanation:"B (states problem) → E (explains why) → A (consequence — explore alternatives) → D (solution identified) → C (benefit of solution).",topic:"Rearrangement"},

  // ── Advanced Error Detection / Grammar (Q63-75) ──
  {id:63,question:"Identify the INCORRECT sentence(s).\nI) The policy measures undertaken by the government has yielded positive results in terms of employment generation.\nII) Were the economy to slip into recession, the central bank would likely cut interest rates aggressively.\nIII) The minister stated that the subsidy burden needs to be rationalized for achieving fiscal targets.",options:{a:"Both I and II",b:"Only III",c:"Only II",d:"Only I",e:"Both I and III"},correct:"d",explanation:"I: 'measures...has' should be 'have' (plural subject). II: Correct — subjunctive mood. III: Correct.",topic:"Error Detection"},
  {id:64,question:"Which sentence is grammatically CORRECT?\nI) The data released by the ministry indicates that industrial production grew by 5.7% in the last quarter.\nII) A delegation comprising members from various industry bodies met with the finance secretary.\nIII) Due to the volatility in global markets, many investors are preferring to park their funds in safer assets.",options:{a:"Only I",b:"Both II and III",c:"Only II",d:"All are correct",e:"Both I and II"},correct:"e",explanation:"I: Correct. II: Correct — 'comprising members' (no 'of'). III: 'are preferring' — stative verb 'prefer' shouldn't normally use continuous tense; should be 'prefer'.",topic:"Error Detection"},
  {id:65,question:"Find INCORRECT sentence(s).\nI) Less number of students appeared for the examination this year compared to last year.\nII) The quantum of non-performing assets in the banking system has reduced significantly over the past two years.\nIII) The central bank's intervention in the currency market prevented further depreciation of the rupee.",options:{a:"Only I",b:"Both I and III",c:"Both I and II",d:"Only II",e:"Only III"},correct:"a",explanation:"I: 'Less number' should be 'Fewer number' or 'A smaller number' (countable noun requires 'fewer'). II and III: Correct.",topic:"Error Detection"},

  // ── Phrase Meaning (Q66-72) ──
  {id:66,question:"The phrase 'fiscal headroom' most nearly means:",options:{a:"A room dedicated to budget planning",b:"Physical space in government buildings",c:"Available capacity within budget to spend or invest",d:"A type of tax exemption for startups",e:"The maximum tax rate allowed"},correct:"c",explanation:"'Fiscal headroom' = the room/capacity within budget constraints to increase spending or reduce taxes.",topic:"Phrase Meaning"},
  {id:67,question:"The phrase 'monetary policy transmission' refers to:",options:{a:"The process by which policy rate changes affect broader economic variables like lending rates and inflation",b:"Transferring money between central banks",c:"Broadcasting RBI decisions on television",d:"RBI physically sending money to banks",e:"Digital transmission of currency notes"},correct:"a",explanation:"Monetary policy transmission = how changes in repo rate flow through to bank lending/deposit rates, credit, demand, and ultimately inflation.",topic:"Phrase Meaning"},
  {id:68,question:"'Crowding out effect' in economics refers to:",options:{a:"Too many people in markets",b:"Excess supply in markets",c:"Government borrowing reducing availability of funds for private investment",d:"Banks refusing to lend",e:"Population pressure on resources"},correct:"c",explanation:"Crowding out: When government borrows heavily, it pushes up interest rates and reduces funds available for private sector investment.",topic:"Phrase Meaning"},
  {id:69,question:"The term 'twin deficit' refers to:",options:{a:"Simultaneous fiscal deficit and current account deficit",b:"Trade deficit with two countries",c:"Budget deficit in two states",d:"Two types of NPA",e:"Two consecutive years of GDP decline"},correct:"a",explanation:"Twin deficit = fiscal deficit (government spending > revenue) + current account deficit (imports > exports).",topic:"Phrase Meaning"},
  {id:70,question:"'Moral hazard' in banking refers to:",options:{a:"Hazardous working conditions in banks",b:"Immoral banking products",c:"Ethical banking practices",d:"When one party takes excessive risks knowing another party bears the cost",e:"Environmental risks of banking operations"},correct:"d",explanation:"Moral hazard: Risk-taking behavior when the risk-taker is insulated from consequences (e.g., banks taking risks knowing government will bail them out).",topic:"Phrase Meaning"},

  // ── More Passage-based / Advanced (Q71-80) ──
  {id:71,question:"[Passage] The concept of financial repression — where governments channel funds to themselves at below-market rates — has re-emerged in policy discussions. In developing economies, statutory requirements like SLR effectively compel banks to hold government securities, thus financing the fiscal deficit at artificially low interest rates. While this provides governments with a cheap source of funding, it _______ the efficient allocation of credit in the economy.\n\nQ: Which word best fills the blank?",options:{a:"enhances",b:"distorts",c:"promotes",d:"facilitates",e:"accelerates"},correct:"b",explanation:"Financial repression 'distorts' efficient credit allocation — it prevents market-determined allocation of funds.",topic:"RC + Cloze"},
  {id:72,question:"[Passage] The concept of financial repression — where governments channel funds to themselves at below-market rates — has re-emerged in policy discussions. In developing economies, statutory requirements like SLR effectively compel banks to hold government securities, thus financing the fiscal deficit at artificially low interest rates. While this provides governments with a cheap source of funding, it distorts the efficient allocation of credit in the economy.\n\nQ: The phrase 'below-market rates' in the passage means:",options:{a:"Rates higher than prevailing market rates",b:"Rates that are lower than what the market would naturally determine",c:"Rates fixed by international organizations",d:"Zero interest rates",e:"Negative interest rates"},correct:"b",explanation:"Below-market rates = rates lower than what free market forces would set.",topic:"RC"},

  // ── Mixed Question Types (Q73-85) ──
  {id:73,question:"Choose the word that fits BOTH blanks:\n1) The audit revealed _______ discrepancies in the company's financial statements.\n2) She showed _______ improvement in her performance after joining the training programme.",options:{a:"slight",b:"marginal",c:"major",d:"gross",e:"material"},correct:"e",explanation:"'Material discrepancies' (significant, substantial) and 'material improvement' (noticeable, significant). Both work in formal context.",topic:"Double Fill"},
  {id:74,question:"Identify the CORRECT sentence(s).\nI) The report underscored the need for strengthening the regulatory architecture governing non-banking financial companies.\nII) Neither the government nor the central bank are willing to assume responsibility for the banking crisis.\nIII) The panel has recommended that the government should considers increasing the allocation for rural development.",options:{a:"Only II",b:"Only III",c:"Both I and III",d:"Both I and II",e:"Only I"},correct:"e",explanation:"I: Correct. II: 'Neither...nor' with nearest subject 'bank' → 'is willing'. III: 'should considers' → 'should consider'.",topic:"Error Detection"},
  {id:75,question:"Arrange to form a coherent paragraph:\nA) This shift is expected to reduce the compliance burden on small businesses.\nB) The government has proposed replacing the existing complex regulatory framework with a simplified compliance regime.\nC) Currently, small businesses are required to navigate a labyrinth of regulations, often at significant cost.\nD) Industry bodies have broadly welcomed the proposal, though they seek clarity on the transitional provisions.\nE) Under the new regime, a single-window clearance mechanism will be introduced for all regulatory approvals.",options:{a:"BCAED",b:"BCEAG",c:"CBEAD",d:"BCEAD",e:"CBAED"},correct:"d",explanation:"B (proposal) → C (current problem) → E (new regime details) → A (expected benefit) → D (industry response).",topic:"Rearrangement"},

  // ── Fill in / Context (Q76-90) ──
  {id:76,question:"Choose the most appropriate word:\n\nThe _______ pace of technological change has made it imperative for financial regulators to constantly update their supervisory frameworks.",options:{a:"declining",b:"sluggish",c:"glacial",d:"modest",e:"relentless"},correct:"e",explanation:"'Relentless' pace = unceasing, persistent, never stopping — technology changes continuously, so regulators must keep updating.",topic:"Cloze"},
  {id:77,question:"Fill in the blank:\n\nThe inclusion of climate-related financial risks in the supervisory framework represents a _______ shift in the approach to financial regulation.",options:{a:"minimal",b:"negligible",c:"retrograde",d:"superficial",e:"paradigm"},correct:"e",explanation:"'Paradigm shift' = fundamental change in approach or underlying assumptions.",topic:"Cloze"},
  {id:78,question:"Identify INCORRECT sentence(s).\nI) The RBI governor's statement had a calming effect on the financial markets, which had been jittery for weeks.\nII) Greater transparency in monetary policy decision-making have enhanced the credibility of the central bank.\nIII) The corporate bond market in India remains relatively underdeveloped compared to those of other emerging market economies.",options:{a:"Only III",b:"Both II and III",c:"Both I and III",d:"Only I",e:"Only II"},correct:"e",explanation:"II: 'transparency...have' should be 'has' (singular subject). I and III are correct.",topic:"Error Detection"},
  {id:79,question:"Choose the connector(s) that can combine:\nI) The new insolvency framework has significantly reduced the time taken for debt resolution.\nII) Recovery rates under the new framework remain below expectations.\ni) Nevertheless\nii) Consequently\niii) However",options:{a:"Both i and iii",b:"All i, ii, and iii",c:"Only i",d:"Only iii",e:"Only ii"},correct:"a",explanation:"Both show contrast: time reduced (positive) BUT recovery rates low (negative). 'Nevertheless' and 'However' work. 'Consequently' shows cause-effect, which doesn't fit.",topic:"Connectors"},
  {id:80,question:"Choose the word that fits BOTH:\n1) The company's decision to _______ from the project surprised many investors.\n2) Please _______ Rs. 5,000 from my savings account.",options:{a:"withdraw",b:"delete",c:"remove",d:"deduct",e:"extract"},correct:"a",explanation:"'Withdraw from the project' (pull out) and 'withdraw Rs. 5,000' (take money out). Both work.",topic:"Double Fill"},

  // ── More Questions (Q81-100) ──
  {id:81,question:"Three sentences given. Find CORRECT one(s).\nI) The depreciation of the rupee against the dollar has made imports costlier, thereby widening the trade deficit.\nII) Every one of the candidates who appeared for the interview were found to be qualified for the position.\nIII) Inspite of the government's best efforts, the inflation rate continues to remain above the comfort zone.",options:{a:"Both I and II",b:"All are correct",c:"Only I",d:"Both I and III",e:"Only II"},correct:"c",explanation:"I: Correct. II: 'Every one...were' → 'was' (singular). III: 'Inspite' should be 'In spite' (two words).",topic:"Error Detection"},
  {id:82,question:"Fill in the blank:\n\nThe committee has been tasked with formulating a comprehensive strategy to _______ the challenges posed by climate change to the agricultural sector.",options:{a:"mitigate",b:"exacerbate",c:"intensify",d:"amplify",e:"worsen"},correct:"a",explanation:"'Mitigate' = reduce the severity of. Formulating strategy to reduce climate change challenges.",topic:"Cloze"},
  {id:83,question:"Choose the word most OPPOSITE to 'nascent' as used in: 'India's nascent fintech sector has attracted significant global investment.'",options:{a:"Mature",b:"Growing",c:"New",d:"Emerging",e:"Developing"},correct:"a",explanation:"Nascent = just beginning to develop. Opposite = mature (fully developed).",topic:"Vocabulary"},
  {id:84,question:"Five sentences jumbled. Correct order?\nA) However, concerns remain about the long-term fiscal implications of these measures.\nB) The government has announced a substantial economic stimulus package.\nC) Tax concessions and credit guarantees form a major component of the package.\nD) Industry leaders have expressed optimism about the package's potential to revive growth.\nE) The package aims to support the sectors worst affected by the economic slowdown.",options:{a:"BECDA",b:"BECDА",c:"BEDCA",d:"BCEDA",e:"BCDEA"},correct:"a",explanation:"B (announcement) → E (aim) → C (components) → D (positive reaction) → A (concerns remain).",topic:"Rearrangement"},
  {id:85,question:"Choose the word that fits BOTH:\n1) The committee decided to _______ the proposal for further deliberation.\n2) The librarian asked students to _______ the books by the end of the week.",options:{a:"table",b:"return",c:"submit",d:"file",e:"deliver"},correct:"b",explanation:"'Return the proposal' (send back for more discussion) and 'return the books' (give back). Both work.",topic:"Double Fill"},
  {id:86,question:"Identify INCORRECT sentence(s).\nI) The amendments to the bankruptcy code are expected to expedite the resolution process for stressed assets.\nII) The committee suggested that the government must allocated additional funds for the rural employment guarantee scheme.\nIII) Neither fiscal expansion nor monetary easing alone can address the structural challenges facing the economy.",options:{a:"Both I and III",b:"Only III",c:"Only I",d:"Only II",e:"Both II and III"},correct:"d",explanation:"II: 'must allocated' → 'must allocate' (base form after modal). I and III are correct.",topic:"Error Detection"},
  {id:87,question:"Fill in the blank:\n\nThe central bank's forward guidance aims to _______ market expectations about the future trajectory of interest rates.",options:{a:"confuse",b:"obscure",c:"anchor",d:"destabilize",e:"unsettle"},correct:"c",explanation:"'Anchor expectations' = stabilize/set firm expectations. Forward guidance helps markets understand RBI's future plans.",topic:"Cloze"},
  {id:88,question:"The phrase 'hard landing' in economic context means:",options:{a:"Stable economic conditions",b:"Physical crash of an aircraft",c:"Gradual economic improvement",d:"A sharp economic slowdown or recession following a period of growth",e:"A successful economic recovery"},correct:"d",explanation:"Hard landing = rapid economic slowdown/recession. Contrasted with 'soft landing' (gradual slowdown).",topic:"Phrase Meaning"},
  {id:89,question:"Choose connector(s) for:\nI) The banking sector has demonstrated improved resilience.\nII) The sector's exposure to sensitive sectors warrants continued vigilance.\ni) Notwithstanding this\nii) Therefore\niii) Even so",options:{a:"All i, ii, and iii",b:"Only i",c:"Both ii and iii",d:"Both i and iii",e:"Only ii"},correct:"d",explanation:"Both sentences contrast positive (resilience) with caution (vigilance needed). 'Notwithstanding this' and 'Even so' show concession. 'Therefore' shows consequence, wrong.",topic:"Connectors"},
  {id:90,question:"Fill in the blank:\n\nThe proliferation of digital lending platforms has _______ the need for a robust regulatory framework to protect consumers from predatory practices.",options:{a:"negated",b:"eliminated",c:"diminished",d:"concealed",e:"underscored"},correct:"e",explanation:"'Underscored the need' = emphasized/highlighted the need. Digital lending growth makes regulation more important.",topic:"Cloze"},
  {id:91,question:"Identify CORRECT sentence(s).\nI) The apex court's verdict is likely to have far-reaching implications for the regulatory architecture of the financial sector.\nII) A slew of reforms has been introduced to streamline the process of doing business in the country.\nIII) The government have announced its intention to divest its stake in several public sector undertakings.",options:{a:"Both II and III",b:"All are correct",c:"Only II",d:"Only I",e:"Both I and II"},correct:"e",explanation:"I: Correct. II: Correct — 'A slew' (singular) → 'has been'. III: 'government have' → 'has' (singular in Indian English).",topic:"Error Detection"},
  {id:92,question:"Choose the word most SIMILAR to 'exigency' as used in: 'The RBI invoked emergency powers in view of the exigency of the situation.'",options:{a:"Urgency",b:"Normality",c:"Simplicity",d:"Insignificance",e:"Routine"},correct:"a",explanation:"Exigency = urgent need or demand. Similar = urgency.",topic:"Vocabulary"},
  {id:93,question:"Choose the word most OPPOSITE to 'augment' as used in: 'Steps were taken to augment the foreign exchange reserves.'",options:{a:"Bolster",b:"Increase",c:"Supplement",d:"Diminish",e:"Enhance"},correct:"d",explanation:"Augment = increase/make larger. Opposite = diminish (make smaller/reduce).",topic:"Vocabulary"},
  {id:94,question:"Fill in the blank:\n\nThe _______ reforms in the banking sector have been aimed at improving governance, strengthening risk management, and enhancing transparency.",options:{a:"superficial",b:"negligible",c:"sweeping",d:"trivial",e:"cosmetic"},correct:"c",explanation:"'Sweeping reforms' = comprehensive, far-reaching changes. Matches the scope described.",topic:"Cloze"},
  {id:95,question:"Choose word for BOTH blanks:\n1) The court decided to _______ the case to the lower tribunal for fresh hearing.\n2) Please _______ the document to the relevant department for processing.",options:{a:"transfer",b:"refer",c:"submit",d:"send",e:"deliver"},correct:"b",explanation:"'Refer the case' (send for further consideration) and 'refer the document' (direct/send to appropriate place). Both work.",topic:"Double Fill"},
  {id:96,question:"Three sentences. Find INCORRECT one(s).\nI) The newly appointed governor bring extensive experience in monetary policy formulation to the central bank.\nII) The twin challenges of inflation and unemployment require a carefully calibrated policy response.\nIII) Had the government acted swiftly, the economic impact of the pandemic could have been significantly mitigated.",options:{a:"Only II",b:"Only III",c:"Both I and III",d:"Only I",e:"Both I and II"},correct:"d",explanation:"I: 'governor bring' → 'brings' (singular subject-verb agreement). II and III are correct.",topic:"Error Detection"},
  {id:97,question:"Arrange sentences to form coherent paragraph:\nA) Consequently, the RBI has been nudging banks to build higher capital buffers.\nB) The global financial crisis of 2008 exposed the vulnerabilities of the banking system.\nC) Adequate capitalization enables banks to absorb losses and continue lending during periods of stress.\nD) It underscored the importance of maintaining robust capital adequacy ratios.\nE) Since then, regulatory standards have been progressively tightened under the Basel III framework.",options:{a:"DEBAC",b:"ABEDC",c:"BDEAC",d:"BACED",e:"BDECA"},correct:"c",explanation:"B (crisis) → D (lesson learned) → E (regulatory response) → A (RBI action) → C (why capital matters).",topic:"Rearrangement"},
  {id:98,question:"Fill in the blank:\n\nThe convergence of banking and technology has given rise to a new _______ of financial service providers that operate at the intersection of finance and technology.",options:{a:"obstacle",b:"barrier",c:"problem",d:"crisis",e:"breed"},correct:"e",explanation:"'A new breed of providers' = a new type/class of companies — common usage for describing emerging categories.",topic:"Cloze"},
  {id:99,question:"Choose the OPPOSITE of 'waning' as used in: 'There are concerns about the waning momentum of economic recovery.'",options:{a:"Fading",b:"Diminishing",c:"Increasing",d:"Declining",e:"Receding"},correct:"c",explanation:"Waning = declining, decreasing. Opposite = increasing/growing.",topic:"Vocabulary"},
  {id:100,question:"Choose connector(s) for:\nI) Financial inclusion has improved significantly with the expansion of banking infrastructure.\nII) Access to credit for marginalized sections remains a persistent challenge.\ni) Yet\nii) Hence\niii) Despite this",options:{a:"All i, ii, and iii",b:"Both i and iii",c:"Only iii",d:"Only ii",e:"Only i"},correct:"b",explanation:"Contrast between improvement and persistent challenge. 'Yet' and 'Despite this' show contrast. 'Hence' shows consequence, which doesn't fit.",topic:"Connectors"},
];
