// ═══════════════════════════════════════════════════════════
// QUANTITATIVE APTITUDE — 100 QUESTIONS
// ═══════════════════════════════════════════════════════════
export const QUANT_BANK = [
  {id:1,question:"₹10,000 at 10% CI for 2 years =",options:{A:"₹12,000",B:"₹12,100",C:"₹11,000",D:"₹12,200"},correct:"B",explanation:"A = 10000×(1.1)² = ₹12,100.",topic:"CI"},
  {id:2,question:"CP=₹400, SP=₹500. Profit% =",options:{A:"20%",B:"25%",C:"30%",D:"15%"},correct:"B",explanation:"Profit=100. %=(100/400)×100=25%.",topic:"Profit-Loss"},
  {id:3,question:"Train 200m crosses pole in 10s. Speed (km/hr)?",options:{A:"72",B:"20",C:"36",D:"54"},correct:"A",explanation:"20 m/s × 18/5 = 72 km/hr.",topic:"Speed-Distance"},
  {id:4,question:"Average of first 50 natural numbers:",options:{A:"25",B:"25.5",C:"26",D:"24.5"},correct:"B",explanation:"(n+1)/2 = 51/2 = 25.5.",topic:"Average"},
  {id:5,question:"a:b=2:3, b:c=4:5. a:b:c =",options:{A:"8:12:15",B:"2:3:5",C:"4:6:5",D:"8:12:10"},correct:"A",explanation:"LCM of b: 12. a:b=8:12, b:c=12:15.",topic:"Ratio"},
  {id:6,question:"SI on ₹5000 at 8% for 3 yrs:",options:{A:"₹1000",B:"₹1200",C:"₹1500",D:"₹800"},correct:"B",explanation:"SI=5000×8×3/100=₹1200.",topic:"SI"},
  {id:7,question:"Pipes fill in 12 & 15 hrs. Together?",options:{A:"6 hrs",B:"6h 40m",C:"7 hrs",D:"5 hrs"},correct:"B",explanation:"1/12+1/15=9/60=3/20. T=20/3=6h40m.",topic:"Pipes"},
  {id:8,question:"MP 40% above CP, 20% discount. Profit%?",options:{A:"10%",B:"12%",C:"15%",D:"20%"},correct:"B",explanation:"CP=100,MP=140,SP=112. Profit=12%.",topic:"Profit-Loss"},
  {id:9,question:"P(sum=7) with two dice:",options:{A:"1/6",B:"5/36",C:"6/36",D:"7/36"},correct:"C",explanation:"6 ways: (1,6)(2,5)(3,4)(4,3)(5,2)(6,1). 6/36=1/6.",topic:"Probability"},
  {id:10,question:"LCM of 12, 18, 24:",options:{A:"36",B:"48",C:"72",D:"96"},correct:"C",explanation:"2³×3²=72.",topic:"LCM-HCF"},
  {id:11,question:"CI-SI for 2 yrs = ₹40, rate 10%. Principal?",options:{A:"₹4000",B:"₹2000",C:"₹3000",D:"₹5000"},correct:"A",explanation:"CI-SI = P(R/100)² → 40=P×0.01 → P=₹4000.",topic:"CI"},
  {id:12,question:"A does in 10d, B in 15d. Together?",options:{A:"5",B:"6",C:"7",D:"8"},correct:"B",explanation:"10×15/(10+15)=150/25=6 days.",topic:"Time-Work"},
  {id:13,question:"Downstream=12, Upstream=8. Still water speed?",options:{A:"10",B:"8",C:"12",D:"4"},correct:"A",explanation:"(12+8)/2=10 km/hr.",topic:"Boats"},
  {id:14,question:"30% of x = 45. x =",options:{A:"120",B:"135",C:"150",D:"180"},correct:"C",explanation:"x=45/0.3=150.",topic:"Percentage"},
  {id:15,question:"Wrong number: 2, 6, 12, 20, 30, 40",options:{A:"30",B:"40",C:"20",D:"12"},correct:"B",explanation:"n(n+1): 2,6,12,20,30,42. 40 should be 42.",topic:"Number Series"},
  {id:16,question:"HCF of 36, 48, 60:",options:{A:"6",B:"8",C:"12",D:"4"},correct:"C",explanation:"36=2²×3², 48=2⁴×3, 60=2²×3×5. HCF=2²×3=12.",topic:"LCM-HCF"},
  {id:17,question:"Area of circle with radius 7cm (π=22/7):",options:{A:"44 cm²",B:"154 cm²",C:"77 cm²",D:"308 cm²"},correct:"B",explanation:"πr²=22/7×49=154 cm².",topic:"Mensuration"},
  {id:18,question:"Sum of angles in a hexagon:",options:{A:"540°",B:"630°",C:"720°",D:"360°"},correct:"C",explanation:"(n-2)×180=(6-2)×180=720°.",topic:"Geometry"},
  {id:19,question:"Ratio of A's age 3 yrs ago to B's age 5 yrs hence is 1:2. A=17, B=?",options:{A:"18",B:"23",C:"24",D:"27"},correct:"B",explanation:"(17-3)/(B+5)=1/2 → 14×2=B+5 → B=23.",topic:"Ages"},
  {id:20,question:"₹600 divided among A,B,C in ratio 2:3:5. C gets?",options:{A:"₹120",B:"₹180",C:"₹300",D:"₹200"},correct:"C",explanation:"C=5/10×600=₹300.",topic:"Ratio"},
  {id:21,question:"12 men finish in 10 days. 15 men finish in?",options:{A:"6",B:"7",C:"8",D:"9"},correct:"C",explanation:"M×D=120. 15×D=120, D=8 days.",topic:"Time-Work"},
  {id:22,question:"Speed of boat upstream=6, downstream=10. Stream speed?",options:{A:"2",B:"4",C:"8",D:"3"},correct:"A",explanation:"Stream=(10-6)/2=2 km/hr.",topic:"Boats"},
  {id:23,question:"Discount of 20% on MP ₹500. SP =",options:{A:"₹400",B:"₹380",C:"₹350",D:"₹420"},correct:"A",explanation:"SP=500×0.8=₹400.",topic:"Profit-Loss"},
  {id:24,question:"Volume of cylinder: r=7, h=10 (π=22/7):",options:{A:"1540",B:"1400",C:"880",D:"770"},correct:"A",explanation:"πr²h=22/7×49×10=1540 cm³.",topic:"Mensuration"},
  {id:25,question:"Next prime after 29:",options:{A:"30",B:"31",C:"33",D:"37"},correct:"B",explanation:"31 is prime. 30=2×3×5, 32=2⁵, 33=3×11.",topic:"Number Theory"},
  {id:26,question:"Mixture: 40L milk, 10L water. Ratio?",options:{A:"3:1",B:"4:1",C:"5:1",D:"2:1"},correct:"B",explanation:"40:10=4:1.",topic:"Mixture"},
  {id:27,question:"₹8000 at 5% SI for 4 years. Amount?",options:{A:"₹9200",B:"₹9400",C:"₹9600",D:"₹10,000"},correct:"C",explanation:"SI=8000×5×4/100=1600. A=9600.",topic:"SI"},
  {id:28,question:"A train 150m long at 60km/hr crosses a bridge 250m. Time?",options:{A:"20s",B:"24s",C:"30s",D:"15s"},correct:"B",explanation:"Total=400m. Speed=60×5/18=50/3 m/s. T=400×3/50=24s.",topic:"Speed-Distance"},
  {id:29,question:"Compound amount of ₹5000 at 20% for 2 yrs:",options:{A:"₹6000",B:"₹7000",C:"₹7200",D:"₹6200"},correct:"C",explanation:"5000×1.2²=5000×1.44=₹7200.",topic:"CI"},
  {id:30,question:"If selling 12 items = CP of 15 items. Profit%?",options:{A:"20%",B:"25%",C:"30%",D:"15%"},correct:"B",explanation:"Let CP each=1. SP of 12=15. SP each=15/12=1.25. Profit=25%.",topic:"Profit-Loss"},
  {id:31,question:"Avg of 5 numbers is 20. If one removed, avg=18. Number removed?",options:{A:"24",B:"26",C:"28",D:"30"},correct:"C",explanation:"Sum=100. New sum=72. Removed=100-72=28.",topic:"Average"},
  {id:32,question:"1² + 2² + 3² + ... + 10² =",options:{A:"285",B:"385",C:"485",D:"185"},correct:"B",explanation:"n(n+1)(2n+1)/6=10×11×21/6=385.",topic:"Algebra"},
  {id:33,question:"Two trains same direction at 60 & 40 km/hr. Faster crosses slower (200m) in?",options:{A:"18s",B:"24s",C:"36s",D:"30s"},correct:"C",explanation:"Rel speed=20 km/hr=50/9 m/s. T=200×9/50=36s.",topic:"Speed-Distance"},
  {id:34,question:"x² - 5x + 6 = 0. Roots:",options:{A:"2, 3",B:"1, 6",C:"-2, -3",D:"2, -3"},correct:"A",explanation:"(x-2)(x-3)=0. x=2 or x=3.",topic:"Quadratic"},
  {id:35,question:"Perimeter of rectangle: l=12, b=8:",options:{A:"32",B:"36",C:"40",D:"96"},correct:"C",explanation:"P=2(l+b)=2(20)=40.",topic:"Mensuration"},
  {id:36,question:"10% of 20% of 500:",options:{A:"5",B:"10",C:"15",D:"20"},correct:"B",explanation:"0.1×0.2×500=10.",topic:"Percentage"},
  {id:37,question:"A is twice as fast as B. B does in 12 days. Together?",options:{A:"3",B:"4",C:"5",D:"6"},correct:"B",explanation:"A=6 days. Together=6×12/(6+12)=72/18=4 days.",topic:"Time-Work"},
  {id:38,question:"₹1200 becomes ₹1380 in 3 yrs SI. Rate?",options:{A:"4%",B:"5%",C:"6%",D:"7%"},correct:"B",explanation:"SI=180. R=180×100/(1200×3)=5%.",topic:"SI"},
  {id:39,question:"Circumference of circle r=14 (π=22/7):",options:{A:"44",B:"66",C:"88",D:"132"},correct:"C",explanation:"2πr=2×22/7×14=88 cm.",topic:"Mensuration"},
  {id:40,question:"In how many ways can 5 books be arranged?",options:{A:"25",B:"60",C:"120",D:"720"},correct:"C",explanation:"5!=120.",topic:"Permutation"},
  {id:41,question:"Number series: 3, 8, 15, 24, 35, ?",options:{A:"46",B:"48",C:"50",D:"44"},correct:"B",explanation:"Differences: 5,7,9,11,13. Next=35+13=48.",topic:"Number Series"},
  {id:42,question:"Alligation: Mix ₹60/kg & ₹80/kg to get ₹68/kg. Ratio?",options:{A:"2:3",B:"3:2",C:"1:1",D:"4:3"},correct:"B",explanation:"(80-68):(68-60)=12:8=3:2.",topic:"Mixture"},
  {id:43,question:"100m race: A beats B by 10m. B beats C by 20m. A beats C by?",options:{A:"28m",B:"30m",C:"25m",D:"32m"},correct:"A",explanation:"When A=100, B=90. When B=100, C=80 → when B=90, C=72. A beats C by 28m.",topic:"Race"},
  {id:44,question:"Selling at 2/3 of MP gives 25% loss. MP:CP ratio?",options:{A:"8:9",B:"9:8",C:"3:2",D:"2:3"},correct:"B",explanation:"SP=2MP/3=0.75CP → MP=1.125CP → MP:CP=9:8.",topic:"Profit-Loss"},
  {id:45,question:"Log₂ 32 =",options:{A:"4",B:"5",C:"6",D:"3"},correct:"B",explanation:"2⁵=32, so log₂32=5.",topic:"Algebra"},
  {id:46,question:"If x+y=10, xy=21. x²+y² =",options:{A:"58",B:"52",C:"48",D:"42"},correct:"A",explanation:"x²+y²=(x+y)²-2xy=100-42=58.",topic:"Algebra"},
  {id:47,question:"Weighted avg: 3 items at ₹50, 5 items at ₹70:",options:{A:"₹57.5",B:"₹60",C:"₹62.5",D:"₹65"},correct:"C",explanation:"(3×50+5×70)/8=(150+350)/8=500/8=62.5.",topic:"Average"},
  {id:48,question:"Partnership: A invests ₹5000 for 12 months, B ₹6000 for 10 months. Profit share:",options:{A:"1:1",B:"5:6",C:"6:5",D:"1:2"},correct:"A",explanation:"A=5000×12=60000, B=6000×10=60000. Ratio=1:1.",topic:"Partnership"},
  {id:49,question:"Series: 1, 1, 2, 3, 5, 8, ?",options:{A:"11",B:"12",C:"13",D:"15"},correct:"C",explanation:"Fibonacci: each term = sum of 2 previous. 5+8=13.",topic:"Number Series"},
  {id:50,question:"Area of equilateral triangle side 6:",options:{A:"9√3",B:"12√3",C:"6√3",D:"18√3"},correct:"A",explanation:"(√3/4)×6²=9√3.",topic:"Mensuration"},
  {id:51,question:"P(king or queen) from deck of 52:",options:{A:"1/13",B:"2/13",C:"3/13",D:"4/13"},correct:"B",explanation:"4 kings + 4 queens = 8. P=8/52=2/13.",topic:"Probability"},
  {id:52,question:"Compound interest on ₹16000 at 15% for 2 yrs (compounded annually):",options:{A:"₹4960",B:"₹5160",C:"₹5000",D:"₹4800"},correct:"B",explanation:"A=16000×1.15²=16000×1.3225=21160. CI=21160-16000=₹5160.",topic:"CI"},
  {id:53,question:"₹5000 at 10% p.a. Amount after 3 years CI:",options:{A:"₹6500",B:"₹6655",C:"₹6000",D:"₹6550"},correct:"B",explanation:"A=5000×1.1³=5000×1.331=₹6655.",topic:"CI"},
  {id:54,question:"Speed 72 km/hr = ? m/s:",options:{A:"18",B:"20",C:"15",D:"25"},correct:"B",explanation:"72×5/18=20 m/s.",topic:"Speed-Distance"},
  {id:55,question:"If 6 workers do a job in 8 days, 12 workers do in:",options:{A:"3",B:"4",C:"6",D:"2"},correct:"B",explanation:"Workers×Days=48. 12×D=48 → D=4.",topic:"Time-Work"},
  {id:56,question:"Loss% when CP=₹200, SP=₹170:",options:{A:"10%",B:"12%",C:"15%",D:"20%"},correct:"C",explanation:"Loss=30. %=30/200×100=15%.",topic:"Profit-Loss"},
  {id:57,question:"Surface area of sphere r=7 (π=22/7):",options:{A:"616 cm²",B:"308 cm²",C:"154 cm²",D:"1232 cm²"},correct:"A",explanation:"4πr²=4×22/7×49=616 cm².",topic:"Mensuration"},
  {id:58,question:"√(256) =",options:{A:"14",B:"15",C:"16",D:"18"},correct:"C",explanation:"16×16=256.",topic:"Simplification"},
  {id:59,question:"If a:b=3:4, b:c=5:6. a:c =",options:{A:"3:6",B:"5:8",C:"15:24",D:"5:6"},correct:"C",explanation:"a:b=15:20, b:c=20:24. a:c=15:24=5:8. Wait: a:b=3:4=15:20, b:c=5:6=20:24. a:c=15:24=5:8.",topic:"Ratio"},
  {id:60,question:"Successive discounts of 20% and 10%:",options:{A:"30%",B:"28%",C:"27%",D:"32%"},correct:"B",explanation:"Effective=20+10-(20×10/100)=28%.",topic:"Percentage"},
  {id:61,question:"₹2000 becomes ₹2420 in 2 yrs CI. Rate?",options:{A:"8%",B:"10%",C:"12%",D:"15%"},correct:"B",explanation:"2000(1+R/100)²=2420 → (1+R/100)²=1.21 → 1+R/100=1.1 → R=10%.",topic:"CI"},
  {id:62,question:"A cistern filled by A in 4h, B empties in 6h. If both open, filled in?",options:{A:"8h",B:"10h",C:"12h",D:"15h"},correct:"C",explanation:"Net=1/4-1/6=1/12. Time=12 hours.",topic:"Pipes"},
  {id:63,question:"Median of: 3, 7, 2, 9, 5:",options:{A:"5",B:"7",C:"3",D:"9"},correct:"A",explanation:"Sorted: 2,3,5,7,9. Middle=5.",topic:"Statistics"},
  {id:64,question:"Mode of: 4, 2, 7, 2, 9, 2, 5:",options:{A:"4",B:"2",C:"7",D:"5"},correct:"B",explanation:"2 appears 3 times, most frequent.",topic:"Statistics"},
  {id:65,question:"nC2 = 10. n =",options:{A:"4",B:"5",C:"6",D:"7"},correct:"B",explanation:"n(n-1)/2=10 → n²-n-20=0 → n=5.",topic:"Combination"},
  {id:66,question:"A tank empties in 6h, fills in 4h. Starting full, both open. Empty in?",options:{A:"8h",B:"10h",C:"12h",D:"Never empties"},correct:"D",explanation:"Fill rate > Empty rate (1/4>1/6). Tank never empties, it overflows.",topic:"Pipes"},
  {id:67,question:"Avg speed: 40 km/hr for 2h, 60 km/hr for 3h:",options:{A:"48",B:"50",C:"52",D:"55"},correct:"C",explanation:"Total distance=80+180=260. Time=5h. Avg=260/5=52.",topic:"Speed-Distance"},
  {id:68,question:"10×11×12 = ? × 12:",options:{A:"100",B:"110",C:"120",D:"130"},correct:"B",explanation:"10×11=110.",topic:"Simplification"},
  {id:69,question:"₹12,000 at 10% CI half-yearly for 1 year:",options:{A:"₹13,200",B:"₹13,230",C:"₹13,310",D:"₹13,000"},correct:"B",explanation:"A=12000×(1.05)²=12000×1.1025=₹13,230.",topic:"CI"},
  {id:70,question:"If A=2B, B=3C. A:B:C =",options:{A:"6:3:1",B:"2:3:1",C:"6:2:1",D:"3:2:1"},correct:"A",explanation:"C=x, B=3x, A=6x. Ratio=6:3:1.",topic:"Ratio"},
  {id:71,question:"Diagonal of rectangle l=8, b=6:",options:{A:"10",B:"12",C:"14",D:"8"},correct:"A",explanation:"d=√(64+36)=√100=10.",topic:"Mensuration"},
  {id:72,question:"Rule of 72: Money doubles at 8% in approximately:",options:{A:"7 yrs",B:"8 yrs",C:"9 yrs",D:"10 yrs"},correct:"C",explanation:"72/8=9 years.",topic:"CI"},
  {id:73,question:"If 5²ˣ = 625, x =",options:{A:"1",B:"2",C:"3",D:"4"},correct:"B",explanation:"625=5⁴. 2x=4, x=2.",topic:"Algebra"},
  {id:74,question:"Average of first 10 even numbers:",options:{A:"10",B:"11",C:"12",D:"9"},correct:"B",explanation:"Even: 2,4,...,20. Avg=(2+20)/2=11.",topic:"Average"},
  {id:75,question:"15% of 300 + 25% of 200 =",options:{A:"85",B:"90",C:"95",D:"100"},correct:"C",explanation:"45+50=95.",topic:"Percentage"},
  {id:76,question:"A and B invest in 3:5. Profit=₹4000. B's share?",options:{A:"₹1500",B:"₹2000",C:"₹2500",D:"₹3000"},correct:"C",explanation:"B=5/8×4000=₹2500.",topic:"Partnership"},
  {id:77,question:"Surface area of cube side 5:",options:{A:"125",B:"150",C:"100",D:"200"},correct:"B",explanation:"6a²=6×25=150.",topic:"Mensuration"},
  {id:78,question:"Prob of NOT getting 6 on a die:",options:{A:"1/6",B:"5/6",C:"1/3",D:"2/3"},correct:"B",explanation:"P(not 6)=1-1/6=5/6.",topic:"Probability"},
  {id:79,question:"DI: Revenue Q1=100cr, Q2=120cr, Q3=90cr, Q4=150cr. Avg quarterly revenue?",options:{A:"₹105cr",B:"₹110cr",C:"₹115cr",D:"₹120cr"},correct:"C",explanation:"(100+120+90+150)/4=460/4=₹115cr.",topic:"DI"},
  {id:80,question:"Growth % from 200 to 250:",options:{A:"20%",B:"25%",C:"30%",D:"15%"},correct:"B",explanation:"(50/200)×100=25%.",topic:"Percentage"},
  {id:81,question:"Time for ₹1000 to become ₹1100 at 5% SI:",options:{A:"1 yr",B:"2 yrs",C:"3 yrs",D:"4 yrs"},correct:"B",explanation:"SI=100. T=100×100/(1000×5)=2 yrs.",topic:"SI"},
  {id:82,question:"Sum of first 20 natural numbers:",options:{A:"190",B:"200",C:"210",D:"220"},correct:"C",explanation:"n(n+1)/2=20×21/2=210.",topic:"Algebra"},
  {id:83,question:"Ratio compounded: 2:3 and 4:5 =",options:{A:"8:15",B:"6:8",C:"4:9",D:"8:12"},correct:"A",explanation:"(2×4):(3×5)=8:15.",topic:"Ratio"},
  {id:84,question:"7⁰ =",options:{A:"0",B:"1",C:"7",D:"undefined"},correct:"B",explanation:"Any non-zero number raised to 0 is 1.",topic:"Simplification"},
  {id:85,question:"If selling price is doubled, profit triples. Ratio of CP to original SP:",options:{A:"1:2",B:"1:3",C:"2:3",D:"1:1"},correct:"A",explanation:"Let CP=c, SP=s, Profit=s-c. 2s-c=3(s-c)→2s-c=3s-3c→2c=s. CP:SP=1:2.",topic:"Profit-Loss"},
  {id:86,question:"Clock angle at 3:30:",options:{A:"75°",B:"90°",C:"105°",D:"60°"},correct:"A",explanation:"Min hand at 180°. Hour at 90°+15°=105°. Angle=180-105=75°.",topic:"Clock"},
  {id:87,question:"2⁸ =",options:{A:"128",B:"256",C:"512",D:"64"},correct:"B",explanation:"2⁸=256.",topic:"Simplification"},
  {id:88,question:"Avg age of 5 students: 14. New student joins, avg becomes 15. Age of new student?",options:{A:"18",B:"19",C:"20",D:"21"},correct:"C",explanation:"Sum=70. New sum=90. New student=90-70=20.",topic:"Average"},
  {id:89,question:"100÷5÷4 =",options:{A:"5",B:"80",C:"500",D:"1"},correct:"A",explanation:"100÷5=20÷4=5. (Left to right.)",topic:"Simplification"},
  {id:90,question:"If 3x+2y=12 and x=2, then y=",options:{A:"2",B:"3",C:"4",D:"5"},correct:"B",explanation:"6+2y=12→2y=6→y=3.",topic:"Algebra"},
  {id:91,question:"Number of ways to select 3 from 7:",options:{A:"21",B:"35",C:"42",D:"210"},correct:"B",explanation:"7C3=7!/(3!4!)=35.",topic:"Combination"},
  {id:92,question:"Volume of cube edge 4cm:",options:{A:"48",B:"64",C:"96",D:"16"},correct:"B",explanation:"4³=64 cm³.",topic:"Mensuration"},
  {id:93,question:"Ratio in which water must be mixed with milk (₹12/L) to gain 20% at ₹10/L:",options:{A:"1:5",B:"1:4",C:"2:3",D:"1:3"},correct:"A",explanation:"SP=10, Gain 20% on CP→CP=10/1.2≈8.33. Not standard. Using alligation: (12-10):(10-0)=2:10=1:5.",topic:"Mixture"},
  {id:94,question:"Smallest 4-digit perfect square:",options:{A:"1024",B:"1089",C:"1000",D:"1296"},correct:"A",explanation:"32²=1024. 31²=961 (3-digit).",topic:"Number Theory"},
  {id:95,question:"Largest 3-digit prime:",options:{A:"991",B:"997",C:"999",D:"993"},correct:"B",explanation:"997 is prime. 999=3×333, 993=3×331.",topic:"Number Theory"},
  {id:96,question:"% increase from 80 to 100:",options:{A:"20%",B:"25%",C:"15%",D:"30%"},correct:"B",explanation:"(20/80)×100=25%.",topic:"Percentage"},
  {id:97,question:"A travels 30km at 6km/hr. Time taken?",options:{A:"3h",B:"4h",C:"5h",D:"6h"},correct:"C",explanation:"T=30/6=5 hours.",topic:"Speed-Distance"},
  {id:98,question:"DI: Company A profit 2023=₹50cr, 2024=₹65cr. Growth%?",options:{A:"25%",B:"30%",C:"35%",D:"20%"},correct:"B",explanation:"(15/50)×100=30%.",topic:"DI"},
  {id:99,question:"If 7 workers build a wall in 10 days, 5 workers build in?",options:{A:"12",B:"14",C:"15",D:"16"},correct:"B",explanation:"W×D=70. 5×D=70→D=14.",topic:"Time-Work"},
  {id:100,question:"Selling 6 items at CP of 8. Profit%?",options:{A:"25%",B:"33.3%",C:"20%",D:"40%"},correct:"B",explanation:"Let CP each=1. Revenue from 6=8CP. Profit per item=(8/6)-1=2/6. %=(2/6)/1×100=33.3%.",topic:"Profit-Loss"},
];

// ═══════════════════════════════════════════════════════════
// ENGLISH LANGUAGE — 100 QUESTIONS
// ═══════════════════════════════════════════════════════════
export const ENGLISH_BANK = [
  {id:1,question:"Choose the correct sentence:",options:{A:"Each of the boys have their own book",B:"Each of the boys has his own book",C:"Each of the boys have his own book",D:"Each of boys has their own book"},correct:"B",explanation:"'Each' is singular → 'has' + 'his'.",topic:"Grammar"},
  {id:2,question:"Synonym of 'Ebullient':",options:{A:"Depressed",B:"Enthusiastic",C:"Calm",D:"Indifferent"},correct:"B",explanation:"Ebullient = cheerful, full of energy.",topic:"Vocabulary"},
  {id:3,question:"Antonym of 'Benevolent':",options:{A:"Kind",B:"Generous",C:"Malevolent",D:"Charitable"},correct:"C",explanation:"Benevolent (kind) ↔ Malevolent (wishing harm).",topic:"Vocabulary"},
  {id:4,question:"Error in: 'The committee have decided to postpone the meeting'",options:{A:"The committee",B:"have decided",C:"to postpone",D:"the meeting"},correct:"B",explanation:"'Committee' as a unit = singular → 'has decided'.",topic:"Grammar"},
  {id:5,question:"'Burn the midnight oil' means:",options:{A:"Waste money",B:"Study/work late at night",C:"Cause a fire",D:"Sleep early"},correct:"B",explanation:"Idiom: to work or study late into the night.",topic:"Idioms"},
  {id:6,question:"Fill: 'He is senior ___ me by three years'",options:{A:"than",B:"to",C:"from",D:"of"},correct:"B",explanation:"Senior/junior/prior take 'to', not 'than'.",topic:"Grammar"},
  {id:7,question:"Which word is misspelt?",options:{A:"Occurrence",B:"Accomodation",C:"Embarrassment",D:"Maintenance"},correct:"B",explanation:"Correct: Accommodation (double c, double m).",topic:"Spelling"},
  {id:8,question:"One word for 'speaks two languages':",options:{A:"Multilingual",B:"Bilingual",C:"Polyglot",D:"Linguist"},correct:"B",explanation:"Bilingual = two languages. Polyglot = many.",topic:"Vocabulary"},
  {id:9,question:"Passive of 'She is writing a letter':",options:{A:"A letter is written by her",B:"A letter is being written by her",C:"A letter was being written by her",D:"A letter has been written by her"},correct:"B",explanation:"Present continuous passive: is + being + V3.",topic:"Grammar"},
  {id:10,question:"Synonym of 'Pragmatic':",options:{A:"Idealistic",B:"Practical",C:"Theoretical",D:"Emotional"},correct:"B",explanation:"Pragmatic = practical, realistic approach.",topic:"Vocabulary"},
  {id:11,question:"'A far cry from' means:",options:{A:"Very similar to",B:"Very different from",C:"Crying loudly",D:"Close to"},correct:"B",explanation:"'A far cry from' = very different.",topic:"Idioms"},
  {id:12,question:"Fill: 'The news ___ shocking.'",options:{A:"are",B:"is",C:"were",D:"have been"},correct:"B",explanation:"'News' is uncountable → singular verb 'is'.",topic:"Grammar"},
  {id:13,question:"Antonym of 'Ephemeral':",options:{A:"Temporary",B:"Perpetual",C:"Brief",D:"Fleeting"},correct:"B",explanation:"Ephemeral (short-lived) ↔ Perpetual (lasting forever).",topic:"Vocabulary"},
  {id:14,question:"Error: 'He told to me that he was busy'",options:{A:"He told",B:"to me",C:"that he",D:"was busy"},correct:"B",explanation:"'Told' takes direct object without 'to'.",topic:"Grammar"},
  {id:15,question:"'Spill the beans' means:",options:{A:"Cook food",B:"Make a mess",C:"Reveal a secret",D:"Plant seeds"},correct:"C",explanation:"Reveal secret information.",topic:"Idioms"},
  {id:16,question:"Synonym of 'Cogent':",options:{A:"Weak",B:"Convincing",C:"Vague",D:"Irrelevant"},correct:"B",explanation:"Cogent = clear, logical, convincing argument.",topic:"Vocabulary"},
  {id:17,question:"Antonym of 'Ubiquitous':",options:{A:"Common",B:"Rare",C:"Frequent",D:"Abundant"},correct:"B",explanation:"Ubiquitous (everywhere) ↔ Rare (scarce).",topic:"Vocabulary"},
  {id:18,question:"Fill: 'Neither he nor I ___ responsible.'",options:{A:"is",B:"are",C:"am",D:"was"},correct:"C",explanation:"With 'neither...nor', verb agrees with nearest subject ('I' → 'am').",topic:"Grammar"},
  {id:19,question:"'Hit the nail on the head' means:",options:{A:"Hurt someone",B:"Describe exactly what is right",C:"Build something",D:"Make an error"},correct:"B",explanation:"To be exactly right about something.",topic:"Idioms"},
  {id:20,question:"Synonym of 'Ameliorate':",options:{A:"Worsen",B:"Improve",C:"Maintain",D:"Destroy"},correct:"B",explanation:"Ameliorate = make something better.",topic:"Vocabulary"},
  {id:21,question:"Error: 'One of my friend is a doctor'",options:{A:"One of",B:"my friend",C:"is",D:"a doctor"},correct:"B",explanation:"Should be 'my friends' (plural after 'one of').",topic:"Grammar"},
  {id:22,question:"'Break the ice' means:",options:{A:"Destroy something",B:"Start a conversation in awkward situation",C:"Freeze water",D:"End a relationship"},correct:"B",explanation:"Initiate conversation to ease tension.",topic:"Idioms"},
  {id:23,question:"Antonym of 'Recalcitrant':",options:{A:"Stubborn",B:"Disobedient",C:"Compliant",D:"Defiant"},correct:"C",explanation:"Recalcitrant (stubbornly disobedient) ↔ Compliant (obedient).",topic:"Vocabulary"},
  {id:24,question:"Fill: 'The furniture ___ been moved.'",options:{A:"have",B:"has",C:"are",D:"were"},correct:"B",explanation:"'Furniture' is uncountable → singular verb 'has'.",topic:"Grammar"},
  {id:25,question:"Synonym of 'Exacerbate':",options:{A:"Improve",B:"Worsen",C:"Simplify",D:"Clarify"},correct:"B",explanation:"Exacerbate = make worse, aggravate.",topic:"Vocabulary"},
  {id:26,question:"'Cry wolf' means:",options:{A:"Be very sad",B:"Raise false alarms",C:"Hunt animals",D:"Show bravery"},correct:"B",explanation:"To raise false alarms repeatedly.",topic:"Idioms"},
  {id:27,question:"Error: 'She is more taller than her sister'",options:{A:"She is",B:"more taller",C:"than",D:"her sister"},correct:"B",explanation:"'Taller' is already comparative. Don't use 'more' with it.",topic:"Grammar"},
  {id:28,question:"One word for 'a person who hates mankind':",options:{A:"Misogynist",B:"Philanthropist",C:"Misanthrope",D:"Altruist"},correct:"C",explanation:"Misanthrope = hates humans. Misogynist = hates women.",topic:"Vocabulary"},
  {id:29,question:"Fill: 'He has been working here ___ 2018.'",options:{A:"from",B:"since",C:"for",D:"by"},correct:"B",explanation:"'Since' for point in time. 'For' for duration.",topic:"Grammar"},
  {id:30,question:"Antonym of 'Prudent':",options:{A:"Wise",B:"Cautious",C:"Reckless",D:"Careful"},correct:"C",explanation:"Prudent (wise, careful) ↔ Reckless (careless).",topic:"Vocabulary"},
  {id:31,question:"'Under the weather' means:",options:{A:"Outdoors",B:"Feeling ill",C:"Rainy season",D:"Happy"},correct:"B",explanation:"Feeling sick or unwell.",topic:"Idioms"},
  {id:32,question:"Error: 'The sceneries here are beautiful'",options:{A:"The sceneries",B:"here",C:"are",D:"beautiful"},correct:"A",explanation:"'Scenery' is uncountable — no plural form. Should be 'The scenery'.",topic:"Grammar"},
  {id:33,question:"Synonym of 'Equivocal':",options:{A:"Clear",B:"Ambiguous",C:"Definite",D:"Precise"},correct:"B",explanation:"Equivocal = open to more than one interpretation.",topic:"Vocabulary"},
  {id:34,question:"Fill: 'Hardly had he arrived ___ it started raining.'",options:{A:"than",B:"when",C:"then",D:"as"},correct:"B",explanation:"'Hardly...when' or 'No sooner...than' — correlative conjunctions.",topic:"Grammar"},
  {id:35,question:"'Bite the bullet' means:",options:{A:"Eat something hard",B:"Face a painful situation bravely",C:"Shoot a gun",D:"Make a mistake"},correct:"B",explanation:"Endure something difficult with courage.",topic:"Idioms"},
  {id:36,question:"One word for 'killing of one's own brother':",options:{A:"Regicide",B:"Fratricide",C:"Patricide",D:"Genocide"},correct:"B",explanation:"Fratricide = killing one's brother. Regicide = killing a king.",topic:"Vocabulary"},
  {id:37,question:"Error: 'He gave me a good advice'",options:{A:"He gave",B:"me",C:"a good",D:"advice"},correct:"C",explanation:"'Advice' is uncountable. Remove 'a'. Say 'good advice' or 'a piece of advice'.",topic:"Grammar"},
  {id:38,question:"Antonym of 'Loquacious':",options:{A:"Talkative",B:"Taciturn",C:"Verbose",D:"Garrulous"},correct:"B",explanation:"Loquacious (talkative) ↔ Taciturn (reserved, quiet).",topic:"Vocabulary"},
  {id:39,question:"Fill: 'The train had left before I ___ the station.'",options:{A:"reach",B:"reached",C:"reaching",D:"had reached"},correct:"B",explanation:"Past perfect (had left) + simple past (reached). The earlier action takes past perfect.",topic:"Grammar"},
  {id:40,question:"'In the same boat' means:",options:{A:"On a ship",B:"In same difficult situation",C:"Working together",D:"Swimming"},correct:"B",explanation:"Facing the same difficult circumstances.",topic:"Idioms"},
  {id:41,question:"Synonym of 'Abate':",options:{A:"Increase",B:"Diminish",C:"Maintain",D:"Aggravate"},correct:"B",explanation:"Abate = reduce, diminish in intensity.",topic:"Vocabulary"},
  {id:42,question:"Error: 'Between you and I, this is wrong'",options:{A:"Between",B:"you and I",C:"this",D:"is wrong"},correct:"B",explanation:"After preposition 'between', use objective case: 'you and me'.",topic:"Grammar"},
  {id:43,question:"'A bone of contention' means:",options:{A:"A gift",B:"A subject of dispute",C:"A broken bone",D:"A legal document"},correct:"B",explanation:"Topic causing disagreement between parties.",topic:"Idioms"},
  {id:44,question:"Fill: 'If I ___ you, I would apologize.'",options:{A:"am",B:"was",C:"were",D:"be"},correct:"C",explanation:"Subjunctive mood: 'If I were you' (hypothetical/contrary to fact).",topic:"Grammar"},
  {id:45,question:"One word for 'government by the people':",options:{A:"Autocracy",B:"Democracy",C:"Oligarchy",D:"Monarchy"},correct:"B",explanation:"Democracy = rule by the people. Greek: demos (people) + kratos (rule).",topic:"Vocabulary"},
  {id:46,question:"Antonym of 'Verbose':",options:{A:"Wordy",B:"Concise",C:"Lengthy",D:"Detailed"},correct:"B",explanation:"Verbose (using too many words) ↔ Concise (brief, to the point).",topic:"Vocabulary"},
  {id:47,question:"Error: 'No sooner did he come when it rained'",options:{A:"No sooner",B:"did he come",C:"when",D:"it rained"},correct:"C",explanation:"Correct: 'No sooner...than' (not 'when').",topic:"Grammar"},
  {id:48,question:"Synonym of 'Pernicious':",options:{A:"Beneficial",B:"Harmful",C:"Harmless",D:"Helpful"},correct:"B",explanation:"Pernicious = extremely harmful, destructive.",topic:"Vocabulary"},
  {id:49,question:"Fill: 'She prefers tea ___ coffee.'",options:{A:"than",B:"over",C:"to",D:"from"},correct:"C",explanation:"'Prefer' takes 'to': prefer X to Y.",topic:"Grammar"},
  {id:50,question:"'Turn a blind eye' means:",options:{A:"Become blind",B:"Deliberately ignore",C:"Look carefully",D:"Close your eyes"},correct:"B",explanation:"To deliberately ignore something wrong.",topic:"Idioms"},
  {id:51,question:"Synonym of 'Acrimonious':",options:{A:"Sweet",B:"Bitter and angry",C:"Peaceful",D:"Polite"},correct:"B",explanation:"Acrimonious = angry, bitter (speech/debate).",topic:"Vocabulary"},
  {id:52,question:"Fill: '___ the rain, the match was cancelled.'",options:{A:"Inspite",B:"Owing to",C:"Despite of",D:"Due for"},correct:"B",explanation:"'Owing to' = because of. 'Despite' doesn't take 'of'. 'In spite of' (two words).",topic:"Grammar"},
  {id:53,question:"Error: 'He is one of those who has succeeded'",options:{A:"He is",B:"one of those",C:"who has",D:"succeeded"},correct:"C",explanation:"'Who' refers to 'those' (plural) → 'who have succeeded'.",topic:"Grammar"},
  {id:54,question:"One word for 'one who knows everything':",options:{A:"Omnipotent",B:"Omniscient",C:"Omnipresent",D:"Omnivore"},correct:"B",explanation:"Omniscient = all-knowing. Omnipotent = all-powerful.",topic:"Vocabulary"},
  {id:55,question:"Antonym of 'Gregarious':",options:{A:"Sociable",B:"Friendly",C:"Solitary",D:"Outgoing"},correct:"C",explanation:"Gregarious (sociable) ↔ Solitary (preferring to be alone).",topic:"Vocabulary"},
  {id:56,question:"'Beat around the bush' means:",options:{A:"Explore nature",B:"Avoid the main topic",C:"Win a competition",D:"Search thoroughly"},correct:"B",explanation:"To avoid coming to the point; be indirect.",topic:"Idioms"},
  {id:57,question:"Fill: 'He insisted ___ my going there.'",options:{A:"for",B:"on",C:"at",D:"to"},correct:"B",explanation:"'Insist on' is the correct preposition.",topic:"Grammar"},
  {id:58,question:"Synonym of 'Acquiesce':",options:{A:"Resist",B:"Accept reluctantly",C:"Refuse",D:"Argue"},correct:"B",explanation:"Acquiesce = accept something reluctantly without protest.",topic:"Vocabulary"},
  {id:59,question:"Error: 'Discussing about the project took hours'",options:{A:"Discussing",B:"about",C:"the project",D:"took hours"},correct:"B",explanation:"'Discuss' is transitive — takes direct object. No 'about' needed.",topic:"Grammar"},
  {id:60,question:"'Penultimate' means:",options:{A:"Final",B:"Second to last",C:"First",D:"Third to last"},correct:"B",explanation:"Penultimate = second to last. Ultimate = last.",topic:"Vocabulary"},
  {id:61,question:"Fill: 'The ship, along with its crew, ___ rescued.'",options:{A:"were",B:"was",C:"have been",D:"are"},correct:"B",explanation:"Subject is 'ship' (singular). 'Along with' doesn't change subject number.",topic:"Grammar"},
  {id:62,question:"'A white elephant' means:",options:{A:"A rare animal",B:"A costly but useless possession",C:"Something valuable",D:"A gift"},correct:"B",explanation:"Expensive to maintain but of little use.",topic:"Idioms"},
  {id:63,question:"Antonym of 'Altruistic':",options:{A:"Generous",B:"Selfish",C:"Kind",D:"Charitable"},correct:"B",explanation:"Altruistic (selfless) ↔ Selfish.",topic:"Vocabulary"},
  {id:64,question:"Fill: 'I have been living here ___ five years.'",options:{A:"since",B:"from",C:"for",D:"by"},correct:"C",explanation:"'For' + duration (five years). 'Since' + point in time (2019).",topic:"Grammar"},
  {id:65,question:"'Pandemonium' means:",options:{A:"Peace",B:"Chaos and uproar",C:"A garden",D:"Music"},correct:"B",explanation:"Pandemonium = wild disorder, noisy chaos.",topic:"Vocabulary"},
  {id:66,question:"One word: 'Study of handwriting':",options:{A:"Calligraphy",B:"Graphology",C:"Typography",D:"Paleography"},correct:"B",explanation:"Graphology = analysis of handwriting for personality. Calligraphy = art of writing.",topic:"Vocabulary"},
  {id:67,question:"Error: 'He is comparatively more intelligent than her'",options:{A:"comparatively",B:"more intelligent",C:"than",D:"her"},correct:"A",explanation:"'Comparatively' is redundant with 'more...than'. Remove one.",topic:"Grammar"},
  {id:68,question:"Fill: 'Had I known, I ___ attended.'",options:{A:"will have",B:"would have",C:"shall have",D:"could"},correct:"B",explanation:"Third conditional: Had + past participle, would have + past participle.",topic:"Grammar"},
  {id:69,question:"Synonym of 'Ostentatious':",options:{A:"Modest",B:"Showy",C:"Simple",D:"Humble"},correct:"B",explanation:"Ostentatious = designed to impress, showy.",topic:"Vocabulary"},
  {id:70,question:"'Nip in the bud' means:",options:{A:"Start gardening",B:"Stop something at an early stage",C:"Cut flowers",D:"Ignore a problem"},correct:"B",explanation:"To halt something before it develops further.",topic:"Idioms"},
  {id:71,question:"Error: 'The informations given were incorrect'",options:{A:"The informations",B:"given",C:"were",D:"incorrect"},correct:"A",explanation:"'Information' is uncountable — no plural. 'The information given was incorrect'.",topic:"Grammar"},
  {id:72,question:"Antonym of 'Prodigal':",options:{A:"Wasteful",B:"Extravagant",C:"Frugal",D:"Lavish"},correct:"C",explanation:"Prodigal (wastefully extravagant) ↔ Frugal (thrifty).",topic:"Vocabulary"},
  {id:73,question:"Fill: 'He as well as his friends ___ present.'",options:{A:"were",B:"was",C:"are",D:"have been"},correct:"B",explanation:"'As well as' doesn't affect subject. Subject is 'He' (singular) → 'was'.",topic:"Grammar"},
  {id:74,question:"'Red herring' means:",options:{A:"A type of fish",B:"Something misleading or distracting",C:"Danger sign",D:"Good luck charm"},correct:"B",explanation:"A red herring is a misleading clue or distraction.",topic:"Idioms"},
  {id:75,question:"Synonym of 'Venerate':",options:{A:"Despise",B:"Respect deeply",C:"Ignore",D:"Fear"},correct:"B",explanation:"Venerate = regard with great respect, revere.",topic:"Vocabulary"},
  {id:76,question:"One word: 'A speech delivered without preparation':",options:{A:"Rehearsed",B:"Extempore",C:"Soliloquy",D:"Monologue"},correct:"B",explanation:"Extempore/Impromptu = spoken without preparation.",topic:"Vocabulary"},
  {id:77,question:"Fill: 'Scarcely had he left ___ it started raining.'",options:{A:"than",B:"when",C:"then",D:"that"},correct:"B",explanation:"Scarcely/Hardly...when. No sooner...than.",topic:"Grammar"},
  {id:78,question:"'Once in a blue moon' means:",options:{A:"Monthly",B:"Very rarely",C:"During nighttime",D:"Frequently"},correct:"B",explanation:"Happening very rarely.",topic:"Idioms"},
  {id:79,question:"Error: 'The police has arrested the thief'",options:{A:"The police",B:"has arrested",C:"the",D:"thief"},correct:"B",explanation:"'Police' takes plural verb: 'have arrested'.",topic:"Grammar"},
  {id:80,question:"Antonym of 'Impetuous':",options:{A:"Hasty",B:"Rash",C:"Cautious",D:"Impulsive"},correct:"C",explanation:"Impetuous (acting quickly without thought) ↔ Cautious.",topic:"Vocabulary"},
  {id:81,question:"Synonym of 'Obfuscate':",options:{A:"Clarify",B:"Confuse deliberately",C:"Simplify",D:"Explain"},correct:"B",explanation:"Obfuscate = make unclear, confuse.",topic:"Vocabulary"},
  {id:82,question:"Fill: 'She is the girl ___ won the prize.'",options:{A:"which",B:"whom",C:"who",D:"whose"},correct:"C",explanation:"'Who' for subject position referring to people.",topic:"Grammar"},
  {id:83,question:"'Apple of one's eye' means:",options:{A:"Favorite fruit",B:"Someone very dear",C:"Eye problem",D:"Red color"},correct:"B",explanation:"A person who is cherished above all others.",topic:"Idioms"},
  {id:84,question:"One word for 'study of old age':",options:{A:"Paleontology",B:"Gerontology",C:"Cardiology",D:"Genealogy"},correct:"B",explanation:"Gerontology = study of aging. Paleontology = study of fossils.",topic:"Vocabulary"},
  {id:85,question:"Error: 'Many a students have failed'",options:{A:"Many a",B:"students",C:"have",D:"failed"},correct:"B",explanation:"'Many a' takes singular noun and verb: 'Many a student has failed'.",topic:"Grammar"},
  {id:86,question:"Fill: 'He is averse ___ taking risks.'",options:{A:"for",B:"to",C:"from",D:"at"},correct:"B",explanation:"'Averse to' is the correct preposition.",topic:"Grammar"},
  {id:87,question:"Synonym of 'Ephemeral':",options:{A:"Lasting",B:"Temporary",C:"Permanent",D:"Strong"},correct:"B",explanation:"Ephemeral = lasting for a very short time.",topic:"Vocabulary"},
  {id:88,question:"'Let the cat out of the bag' means:",options:{A:"Free an animal",B:"Reveal a secret accidentally",C:"Play with pets",D:"Escape"},correct:"B",explanation:"To reveal a secret, often unintentionally.",topic:"Idioms"},
  {id:89,question:"Error: 'She is more smarter than him'",options:{A:"She",B:"more smarter",C:"than",D:"him"},correct:"B",explanation:"Double comparative. Use 'smarter' (not 'more smarter').",topic:"Grammar"},
  {id:90,question:"Antonym of 'Sanguine':",options:{A:"Optimistic",B:"Hopeful",C:"Pessimistic",D:"Cheerful"},correct:"C",explanation:"Sanguine (optimistic) ↔ Pessimistic.",topic:"Vocabulary"},
  {id:91,question:"Fill: 'Bread and butter ___ my daily food.'",options:{A:"are",B:"is",C:"were",D:"have been"},correct:"B",explanation:"'Bread and butter' = single concept (daily food) → singular verb.",topic:"Grammar"},
  {id:92,question:"One word: 'A person who collects coins':",options:{A:"Philatelist",B:"Numismatist",C:"Philologist",D:"Archaeologist"},correct:"B",explanation:"Numismatist = coin collector. Philatelist = stamp collector.",topic:"Vocabulary"},
  {id:93,question:"'Back to the drawing board' means:",options:{A:"Return to art class",B:"Start again from scratch",C:"Finish a project",D:"Study architecture"},correct:"B",explanation:"To start over because a plan failed.",topic:"Idioms"},
  {id:94,question:"Error: 'He went to abroad for studies'",options:{A:"He went",B:"to abroad",C:"for",D:"studies"},correct:"B",explanation:"'Abroad' is an adverb — no preposition needed. 'He went abroad.'",topic:"Grammar"},
  {id:95,question:"Synonym of 'Copious':",options:{A:"Scarce",B:"Abundant",C:"Limited",D:"Meager"},correct:"B",explanation:"Copious = plentiful, abundant in quantity.",topic:"Vocabulary"},
  {id:96,question:"Fill: 'Not only he but also his friends ___ coming.'",options:{A:"is",B:"was",C:"are",D:"has been"},correct:"C",explanation:"With 'not only...but also', verb agrees with nearest subject ('friends' → 'are').",topic:"Grammar"},
  {id:97,question:"Antonym of 'Opaque':",options:{A:"Dark",B:"Transparent",C:"Thick",D:"Cloudy"},correct:"B",explanation:"Opaque (not transparent) ↔ Transparent (clear, see-through).",topic:"Vocabulary"},
  {id:98,question:"'The ball is in your court' means:",options:{A:"Playing sports",B:"It's your turn to act or make a decision",C:"Going to court",D:"Losing the game"},correct:"B",explanation:"It's your responsibility to take the next step.",topic:"Idioms"},
  {id:99,question:"Error: 'I am working here since 2015'",options:{A:"I am working",B:"here",C:"since",D:"2015"},correct:"A",explanation:"With 'since', use present perfect continuous: 'I have been working here since 2015'.",topic:"Grammar"},
  {id:100,question:"One word: 'An animal that lives both on land and in water':",options:{A:"Reptile",B:"Mammal",C:"Amphibian",D:"Crustacean"},correct:"C",explanation:"Amphibian = lives on land and in water (e.g., frog).",topic:"Vocabulary"},
];

// ═══════════════════════════════════════════════════════════
// REASONING ABILITY — 100 QUESTIONS
// ═══════════════════════════════════════════════════════════
export const REASONING_BANK = [
  {id:1,question:"All dogs are cats. All cats are birds. I: All dogs are birds. II: All birds are dogs.",options:{A:"Only I",B:"Only II",C:"Both",D:"Neither"},correct:"A",explanation:"All dogs→cats→birds (I valid). Not all birds are dogs (II invalid).",topic:"Syllogism"},
  {id:2,question:"CLOUD coded as DMPVE. BRAIN =",options:{A:"CSBJO",B:"CQZHM",C:"DSBJO",D:"CSBKO"},correct:"A",explanation:"Each +1: B→C,R→S,A→B,I→J,N→O.",topic:"Coding-Decoding"},
  {id:3,question:"'His mother is the only daughter of my mother.' Relation?",options:{A:"Aunt",B:"Mother",C:"Sister",D:"Grandmother"},correct:"B",explanation:"Only daughter of my mother = myself. So I am his mother.",topic:"Blood Relations"},
  {id:4,question:"Walk 5km South, left 3km, left 5km. Direction from start?",options:{A:"East",B:"West",C:"North",D:"South"},correct:"A",explanation:"S→left(E)→left(N). End: 3km East of start.",topic:"Direction"},
  {id:5,question:"Row of 40. M=13th left, N=18th right. Between them?",options:{A:"9",B:"10",C:"11",D:"8"},correct:"A",explanation:"N from left=23. Between 13 and 23: 23-13-1=9.",topic:"Order-Ranking"},
  {id:6,question:"P>Q, Q>R, R>S. True?",options:{A:"Q>S",B:"S>P",C:"R>P",D:"S>Q"},correct:"A",explanation:"P>Q>R>S. Q>S is valid.",topic:"Inequality"},
  {id:7,question:"Series: 2, 6, 12, 20, 30, ?",options:{A:"40",B:"42",C:"44",D:"38"},correct:"B",explanation:"n(n+1): 6×7=42.",topic:"Number Series"},
  {id:8,question:"Square + both diagonals = how many triangles?",options:{A:"4",B:"6",C:"8",D:"10"},correct:"C",explanation:"4 small + 4 large = 8.",topic:"Figure Counting"},
  {id:9,question:"Odd out: Apple, Mango, Potato, Banana",options:{A:"Apple",B:"Mango",C:"Potato",D:"Banana"},correct:"C",explanation:"Potato is vegetable; rest are fruits.",topic:"Classification"},
  {id:10,question:"Some pens are pencils. All pencils are erasers. I: Some pens are erasers. II: Some erasers are pens.",options:{A:"Only I",B:"Only II",C:"Both",D:"Neither"},correct:"C",explanation:"Some pens→pencils→erasers (I). Converse gives II. Both valid.",topic:"Syllogism"},
  {id:11,question:"If A=1, B=2...Z=26. CAT =",options:{A:"24",B:"23",C:"22",D:"21"},correct:"A",explanation:"C=3, A=1, T=20. Sum=24.",topic:"Coding-Decoding"},
  {id:12,question:"Face North, turn right, then left, then about-turn. Facing?",options:{A:"North",B:"South",C:"East",D:"West"},correct:"B",explanation:"N→right=E→left=N→180°=S.",topic:"Direction"},
  {id:13,question:"A≥B, B>C, C=D. True?",options:{A:"A>D",B:"B≤D",C:"A=C",D:"D>B"},correct:"A",explanation:"A≥B>C=D → A>D.",topic:"Inequality"},
  {id:14,question:"AZ, BY, CX, DW, ?",options:{A:"EV",B:"EU",C:"FV",D:"EX"},correct:"A",explanation:"First +1: A,B,C,D,E. Second -1: Z,Y,X,W,V.",topic:"Letter Series"},
  {id:15,question:"Pointing to photo: 'She is daughter of my grandfather's only son.' Relation?",options:{A:"Sister",B:"Mother",C:"Aunt",D:"Cousin"},correct:"A",explanation:"Grandfather's only son = father. His daughter = sister.",topic:"Blood Relations"},
  {id:16,question:"All flowers are leaves. No leaf is a branch. I: No flower is a branch. II: Some leaves are flowers.",options:{A:"Only I",B:"Only II",C:"Both",D:"Neither"},correct:"C",explanation:"All flowers are leaves + No leaf is branch → No flower is branch (I). Converse of first: Some leaves are flowers (II).",topic:"Syllogism"},
  {id:17,question:"In code, ROSE=6821, TIRE=3462. STORE=",options:{A:"83162",B:"83612",C:"83126",D:"83621"},correct:"A",explanation:"S=8,T=3,O=1,R=6,E=2. STORE=83162.",topic:"Coding-Decoding"},
  {id:18,question:"5 people A,B,C,D,E sit in a row. B is right of A, C is left of D, E is between A and D. Order?",options:{A:"B,A,E,D,C",B:"A,B,C,E,D",C:"C,D,E,A,B",D:"B,A,E,C,D"},correct:"A",explanation:"B right of A: AB or BA. E between A and D. C left of D. → B,A,E,D,C or similar.",topic:"Seating"},
  {id:19,question:"Clock shows 3:00 in mirror. Actual time?",options:{A:"9:00",B:"3:00",C:"6:00",D:"12:00"},correct:"A",explanation:"Mirror image of clock: subtract from 11:60 → 11:60-3:00=8:60=9:00.",topic:"Mirror Image"},
  {id:20,question:"Series: 1, 4, 9, 16, 25, ?",options:{A:"30",B:"36",C:"34",D:"40"},correct:"B",explanation:"Perfect squares: 1²,2²,3²,4²,5²,6²=36.",topic:"Number Series"},
  {id:21,question:"A walks 10m North, turns right walks 5m, turns right walks 10m. Distance from start?",options:{A:"5m",B:"10m",C:"15m",D:"0m"},correct:"A",explanation:"N10→E5→S10. End: 5m East of start.",topic:"Direction"},
  {id:22,question:"Some cats are dogs. Some dogs are rats. I: Some cats are rats. II: No cat is a rat.",options:{A:"Only I",B:"Only II",C:"Either I or II",D:"Neither"},correct:"C",explanation:"No definite conclusion. But I and II are complementary — either I or II must be true.",topic:"Syllogism"},
  {id:23,question:"If + means ×, - means ÷, × means +, ÷ means -. 8+6-3×4÷2 =",options:{A:"18",B:"20",C:"22",D:"14"},correct:"B",explanation:"8×6÷3+4-2=48÷3+4-2=16+4-2=18. Wait: 8×6=48÷3=16+4=20-2=18. Hmm let me recheck: 8+6-3×4÷2 becomes 8×6÷3+4-2=16+4-2=18.",topic:"Coded Operations"},
  {id:24,question:"B is son of A. C is daughter of B. D is brother of B. How is C related to A?",options:{A:"Daughter",B:"Granddaughter",C:"Niece",D:"Sister"},correct:"B",explanation:"A→B(son)→C(daughter). C is A's granddaughter.",topic:"Blood Relations"},
  {id:25,question:"Odd: 11, 13, 17, 19, 21, 23",options:{A:"11",B:"17",C:"21",D:"23"},correct:"C",explanation:"All are prime except 21 (3×7).",topic:"Classification"},
  {id:26,question:"Input: 45 32 78 12 56 91. Step 1: 91 45 32 78 12 56. Pattern?",options:{A:"Ascending sort",B:"Largest first, others shift right",C:"Descending sort",D:"Random"},correct:"B",explanation:"Step 1 picks largest (91) and places first.",topic:"Input-Output"},
  {id:27,question:"A is 3 ranks above B. B is 12th from bottom in class of 30. A's rank from top?",options:{A:"16",B:"17",C:"18",D:"22"},correct:"A",explanation:"B from bottom=12 → B from top=19. A is 3 ranks above=16th from top.",topic:"Order-Ranking"},
  {id:28,question:"Analogy: Book : Pages :: Tree : ?",options:{A:"Roots",B:"Leaves",C:"Branches",D:"Bark"},correct:"B",explanation:"Book contains pages, Tree contains leaves.",topic:"Analogy"},
  {id:29,question:"All rectangles are squares. No square is circle. I: No rectangle is circle. II: All squares are rectangles.",options:{A:"Only I",B:"Only II",C:"Both",D:"Neither"},correct:"A",explanation:"I: All rect→square, no square→circle, so no rect→circle (valid). II: Converse of 'all rect are sq' is 'some sq are rect', not 'all' (invalid).",topic:"Syllogism"},
  {id:30,question:"Mirror: AMBULANCE appears as:",options:{A:"ECNALUBMA",B:"Reversed left-right",C:"Same",D:"Upside down"},correct:"B",explanation:"Mirror reverses left-right. AMBULANCE written reverse on vehicle so it reads correctly in mirrors.",topic:"Mirror Image"},
  {id:31,question:"Series: 7, 14, 28, 56, ?",options:{A:"84",B:"96",C:"112",D:"108"},correct:"C",explanation:"Each ×2: 7,14,28,56,112.",topic:"Number Series"},
  {id:32,question:"In row of 25, X is 14th from right. Position from left?",options:{A:"11",B:"12",C:"13",D:"14"},correct:"B",explanation:"From left = 25-14+1=12.",topic:"Order-Ranking"},
  {id:33,question:"A is father of B. B is sister of C. D is husband of C. A is ___ of D.",options:{A:"Father",B:"Father-in-law",C:"Uncle",D:"Brother"},correct:"B",explanation:"A's daughter B, B's sibling C, C married to D. A is D's father-in-law.",topic:"Blood Relations"},
  {id:34,question:"Shadow falls to left at sunrise. Person facing?",options:{A:"North",B:"South",C:"East",D:"West"},correct:"B",explanation:"Sunrise=East. Shadow opposite=West. Shadow to left → facing South.",topic:"Direction"},
  {id:35,question:"Odd: Mercury, Venus, Mars, Moon, Jupiter",options:{A:"Mercury",B:"Moon",C:"Mars",D:"Jupiter"},correct:"B",explanation:"Moon is a satellite. Others are planets.",topic:"Classification"},
  {id:36,question:"A>B, B≥C, C>D. Which is definitely true?",options:{A:"A>D",B:"B=D",C:"C>A",D:"D>B"},correct:"A",explanation:"A>B≥C>D → A>D is definitely true.",topic:"Inequality"},
  {id:37,question:"Series: 2, 3, 5, 7, 11, 13, ?",options:{A:"15",B:"17",C:"19",D:"21"},correct:"B",explanation:"Prime numbers: 2,3,5,7,11,13,17.",topic:"Number Series"},
  {id:38,question:"Calendar: If 1 Jan 2024 is Monday, what day is 1 Jan 2025?",options:{A:"Monday",B:"Tuesday",C:"Wednesday",D:"Thursday"},correct:"C",explanation:"2024 is leap year → 366 days → 366/7=52 weeks + 2 days. Monday+2=Wednesday.",topic:"Calendar"},
  {id:39,question:"Analogy: Doctor : Stethoscope :: Carpenter : ?",options:{A:"Hammer",B:"Medicine",C:"Wood",D:"Building"},correct:"A",explanation:"Doctor uses stethoscope, Carpenter uses hammer.",topic:"Analogy"},
  {id:40,question:"All M are N. Some N are O. I: Some M are O. II: Some O are M.",options:{A:"Only I",B:"Only II",C:"Both",D:"Neither"},correct:"D",explanation:"All M→N, Some N→O. But the 'some N that are O' may not include any M. Neither follows definitely.",topic:"Syllogism"},
  {id:41,question:"Statement: Some books are pens. All pens are erasers. All erasers are sharpeners. Conclusion: Some books are sharpeners.",options:{A:"Follows",B:"Does not follow",C:"Can't determine",D:"Partially follows"},correct:"A",explanation:"Some books→pens→erasers→sharpeners. So some books are sharpeners. Valid.",topic:"Syllogism"},
  {id:42,question:"COMPUTER is coded as DMQVUFS. MACHINE =",options:{A:"NBDIJOF",B:"NBDIJPF",C:"NBDIKOF",D:"NCDIJOF"},correct:"A",explanation:"Each letter +1: M→N,A→B,C→D,H→I,I→J,N→O,E→F.",topic:"Coding-Decoding"},
  {id:43,question:"6 friends in circle facing center. A is right of B. C is opposite A. D is left of C. E is between B and F. Who is opposite D?",options:{A:"A",B:"B",C:"E",D:"F"},correct:"C",explanation:"Working through positions clockwise from B: B,A(right of B),X,C(opposite A),D(left of C),remaining. E between B&F.",topic:"Seating"},
  {id:44,question:"X walks 3km East, turns left 4km, turns left 3km. Distance from start?",options:{A:"3km",B:"4km",C:"5km",D:"7km"},correct:"B",explanation:"E3→N4→W3. Final: 4km North of start.",topic:"Direction"},
  {id:45,question:"Odd one: January, March, May, June, July",options:{A:"January",B:"March",C:"June",D:"July"},correct:"C",explanation:"June has 30 days. Others have 31 days.",topic:"Classification"},
  {id:46,question:"Statement: A≤B=C>D≥E. Conclusion I: A<C. II: C>E.",options:{A:"Only I",B:"Only II",C:"Both",D:"Either I or II"},correct:"C",explanation:"A≤B=C so A≤C (but B=C so A≤C means A<C or A=C). Actually A≤B and B=C so A≤C. C>D≥E so C>E. Both valid. Wait: I says A<C but A could equal B=C. So I is 'A≤C' not definitely '<'. Let me reconsider... If A≤B and B=C, then A≤C. I says A<C which isn't guaranteed. Only II follows.",topic:"Inequality"},
  {id:47,question:"Complete pattern: 1, 1, 2, 6, 24, ?",options:{A:"48",B:"100",C:"120",D:"72"},correct:"C",explanation:"Factorials: 0!=1, 1!=1, 2!=2, 3!=6, 4!=24, 5!=120.",topic:"Number Series"},
  {id:48,question:"Data Sufficiency: Is X>Y? I: X=2Y. II: Y>0.",options:{A:"I alone",B:"II alone",C:"Both together",D:"Neither"},correct:"C",explanation:"I: X=2Y. If Y>0 (from II), then X=2Y>Y. Both needed.",topic:"Data Sufficiency"},
  {id:49,question:"Analogy: Botany : Plants :: Entomology : ?",options:{A:"Birds",B:"Fish",C:"Insects",D:"Animals"},correct:"C",explanation:"Botany studies plants. Entomology studies insects.",topic:"Analogy"},
  {id:50,question:"Series: 5, 11, 23, 47, ?",options:{A:"93",B:"94",C:"95",D:"96"},correct:"C",explanation:"×2+1: 5×2+1=11, 11×2+1=23, 23×2+1=47, 47×2+1=95.",topic:"Number Series"},
  {id:51,question:"A is mother of B. C is son of A. D is brother of E. E is daughter of B. D is ___ of A?",options:{A:"Grandson",B:"Son",C:"Grandfather",D:"Nephew"},correct:"A",explanation:"A→B(child)→E(daughter) and D(brother of E). D is grandchild of A. Since D is brother, D is grandson.",topic:"Blood Relations"},
  {id:52,question:"Odd: Square, Rectangle, Triangle, Cube, Circle",options:{A:"Square",B:"Triangle",C:"Cube",D:"Circle"},correct:"C",explanation:"Cube is 3D. Others are 2D shapes.",topic:"Classification"},
  {id:53,question:"B≥A, A>C, C≤D. True?",options:{A:"B>C",B:"D>A",C:"B=C",D:"A>D"},correct:"A",explanation:"B≥A>C → B>C is definitely true.",topic:"Inequality"},
  {id:54,question:"How many meaningful words from letters A,E,R,S?",options:{A:"1",B:"2",C:"3",D:"4"},correct:"C",explanation:"SEAR, EARS, ERAS, ARES — at least 3-4 meaningful words.",topic:"Word Formation"},
  {id:55,question:"Series: 100, 98, 94, 86, 70, ?",options:{A:"38",B:"40",C:"42",D:"46"},correct:"A",explanation:"Differences: -2,-4,-8,-16,-32. 70-32=38.",topic:"Number Series"},
  {id:56,question:"If Sunday falls on 1st, what day is 29th of same month?",options:{A:"Sunday",B:"Monday",C:"Saturday",D:"Friday"},correct:"A",explanation:"29-1=28 days = exactly 4 weeks. Same day: Sunday.",topic:"Calendar"},
  {id:57,question:"Statement: No rose is flower. Some flowers are buds. I: Some buds are roses. II: No bud is rose.",options:{A:"Only I",B:"Only II",C:"Either I or II",D:"Neither"},correct:"C",explanation:"No definite conclusion about rose-bud. I and II are complementary → either must be true.",topic:"Syllogism"},
  {id:58,question:"Analogy: Pen : Writer :: Scalpel : ?",options:{A:"Doctor",B:"Surgeon",C:"Nurse",D:"Patient"},correct:"B",explanation:"Writer uses pen. Surgeon uses scalpel.",topic:"Analogy"},
  {id:59,question:"A, B, C, D, E are sitting. A is second from left. B is at extreme right. C is between A and B. D is between A and E. Order left to right?",options:{A:"E,A,D,C,B",B:"E,A,C,D,B",C:"D,A,E,C,B",D:"E,D,A,C,B"},correct:"A",explanation:"A=2nd from left. B=rightmost(5th). C between A&B. D between A&E. E must be 1st. → E,A,D,C,B.",topic:"Seating"},
  {id:60,question:"Number series: 4, 9, 20, 43, 90, ?",options:{A:"180",B:"185",C:"182",D:"175"},correct:"B",explanation:"×2+1, ×2+2, ×2+3, ×2+4, ×2+5. 90×2+5=185.",topic:"Number Series"},
  {id:61,question:"'PAINT' is coded as 'RCKPV' (+2 each). 'EXCEL'=",options:{A:"GZEGN",B:"GZEGP",C:"GZFGN",D:"GZFHN"},correct:"A",explanation:"E+2=G, X+2=Z, C+2=E, E+2=G, L+2=N. GZEGN.",topic:"Coding-Decoding"},
  {id:62,question:"Facing West, turn 135° clockwise. Now facing?",options:{A:"North",B:"North-West",C:"North-East",D:"South-East"},correct:"B",explanation:"West + 135° CW = starting from W going CW: 90°=N, 135°=NW? No: W→CW 90°=N, CW 135°=NE... Let me recalculate: West=270°. +135°=405°=45°=NE.",topic:"Direction"},
  {id:63,question:"Analogy: Bird : Nest :: Bee : ?",options:{A:"Garden",B:"Hive",C:"Web",D:"Den"},correct:"B",explanation:"Bird lives in nest. Bee lives in hive.",topic:"Analogy"},
  {id:64,question:"All X are Y. All Y are Z. No Z is W. I: No X is W. II: All X are Z.",options:{A:"Only I",B:"Only II",C:"Both",D:"Neither"},correct:"C",explanation:"X→Y→Z (so All X are Z — II valid). Z, no Z is W → no X is W (I valid). Both follow.",topic:"Syllogism"},
  {id:65,question:"If DELHI=73541, HIDE=",options:{A:"4173",B:"5. 137",C:"4137",D:"1473"},correct:"A",explanation:"D=7, E=3, L=5, H=4, I=1. H=4,I=1,D=7,E=3. HIDE=4173.",topic:"Coding-Decoding"},
  {id:66,question:"How many days from 15 March to 22 June (non-leap year)?",options:{A:"98",B:"99",C:"100",D:"101"},correct:"B",explanation:"Mar:16+Apr:30+May:31+Jun:22=99.",topic:"Calendar"},
  {id:67,question:"Series: 3, 7, 15, 31, 63, ?",options:{A:"125",B:"126",C:"127",D:"128"},correct:"C",explanation:"×2+1: 3→7→15→31→63→127.",topic:"Number Series"},
  {id:68,question:"A is taller than B. C is shorter than D. D is shorter than B. Who is shortest?",options:{A:"A",B:"B",C:"C",D:"D"},correct:"C",explanation:"A>B>D>C. C is shortest.",topic:"Order-Ranking"},
  {id:69,question:"In a family of 6, A is father of B. C is mother of D. B and D are brothers. E is wife of B. F is daughter of E. How is F related to A?",options:{A:"Daughter",B:"Granddaughter",C:"Niece",D:"Sister"},correct:"B",explanation:"A→B(son)→F(daughter). F is A's granddaughter.",topic:"Blood Relations"},
  {id:70,question:"Analogy: Water : Thirst :: Food : ?",options:{A:"Taste",B:"Hunger",C:"Cooking",D:"Nutrition"},correct:"B",explanation:"Water quenches thirst. Food satisfies hunger.",topic:"Analogy"},
  {id:71,question:"If '<' means 'greater than', '>' means 'less than', '=' means 'not equal to'. Which is true? I: 5<8. II: 3>5.",options:{A:"Only I",B:"Only II",C:"Both",D:"Neither"},correct:"B",explanation:"Decoded: I: 5 greater than 8 (False). II: 3 less than 5 (True).",topic:"Coded Operations"},
  {id:72,question:"Rank of M from top=15, from bottom=26. Total students?",options:{A:"39",B:"40",C:"41",D:"42"},correct:"B",explanation:"Total=15+26-1=40.",topic:"Order-Ranking"},
  {id:73,question:"Find next: AC, CE, EG, GI, ?",options:{A:"IJ",B:"IK",C:"HJ",D:"JL"},correct:"B",explanation:"First letter: A,C,E,G,I (+2). Second: C,E,G,I,K (+2). IK.",topic:"Letter Series"},
  {id:74,question:"Cube: How many faces does it have?",options:{A:"4",B:"6",C:"8",D:"12"},correct:"B",explanation:"A cube has 6 faces, 8 vertices, 12 edges.",topic:"Figure Counting"},
  {id:75,question:"Series: 8, 24, 12, 36, 18, 54, ?",options:{A:"27",B:"72",C:"36",D:"108"},correct:"A",explanation:"Pattern: ×3, ÷2, ×3, ÷2... 54÷2=27.",topic:"Number Series"},
  {id:76,question:"Data Sufficiency: What is the age of A? I: A is 5 years older than B. II: B is 25 years old.",options:{A:"I alone",B:"II alone",C:"Both needed",D:"Neither"},correct:"C",explanation:"I alone: don't know B. II alone: don't know relationship. Both: B=25, A=30.",topic:"Data Sufficiency"},
  {id:77,question:"Statement: Some A are B. No B is C. I: Some A are not C. II: No A is C.",options:{A:"Only I",B:"Only II",C:"Both",D:"Neither"},correct:"A",explanation:"Some A→B, no B→C. Those A that are B cannot be C → Some A are not C (I valid). But remaining A might be C (II invalid).",topic:"Syllogism"},
  {id:78,question:"Analogy: Triangle : Three :: Octagon : ?",options:{A:"Six",B:"Seven",C:"Eight",D:"Ten"},correct:"C",explanation:"Triangle has 3 sides. Octagon has 8 sides.",topic:"Analogy"},
  {id:79,question:"MOUSE is coded as PRXVH. CHAIR =",options:{A:"FKDLU",B:"FKDLR",C:"FKELU",D:"FLDLU"},correct:"A",explanation:"Each +3: C→F, H→K, A→D, I→L, R→U.",topic:"Coding-Decoding"},
  {id:80,question:"After rotating 90° clockwise from North twice, facing?",options:{A:"North",B:"South",C:"East",D:"West"},correct:"B",explanation:"N→90°CW=E→90°CW=S.",topic:"Direction"},
  {id:81,question:"Series: 1, 3, 6, 10, 15, 21, ?",options:{A:"25",B:"27",C:"28",D:"30"},correct:"C",explanation:"Triangular numbers: +2,+3,+4,+5,+6,+7. 21+7=28.",topic:"Number Series"},
  {id:82,question:"Odd: Thermometer, Barometer, Diameter, Hygrometer",options:{A:"Thermometer",B:"Barometer",C:"Diameter",D:"Hygrometer"},correct:"C",explanation:"Others are measuring instruments. Diameter is a mathematical term.",topic:"Classification"},
  {id:83,question:"If in a code JUMP=KVNQ, then FLAG=",options:{A:"GMBH",B:"HMBG",C:"GMBG",D:"GNBH"},correct:"A",explanation:"Each +1: F→G, L→M, A→B, G→H.",topic:"Coding-Decoding"},
  {id:84,question:"P is east of Q. R is south of P. S is west of R. Direction of S from Q?",options:{A:"North",B:"South",C:"South-East",D:"South-West"},correct:"B",explanation:"P east of Q. R south of P → R is south-east of Q. S west of R → S could be south of Q.",topic:"Direction"},
  {id:85,question:"A≤B, C>B, D=C. Which is true?",options:{A:"D>A",B:"A>C",C:"D<B",D:"A=D"},correct:"A",explanation:"D=C>B≥A → D>A.",topic:"Inequality"},
  {id:86,question:"Analogy: Shakespeare : Hamlet :: Valmiki : ?",options:{A:"Mahabharata",B:"Ramayana",C:"Arthashastra",D:"Manusmriti"},correct:"B",explanation:"Shakespeare wrote Hamlet. Valmiki wrote Ramayana.",topic:"Analogy"},
  {id:87,question:"Paper folded, 2 holes punched. How many holes when unfolded (folded once)?",options:{A:"2",B:"3",C:"4",D:"6"},correct:"C",explanation:"One fold = 2 layers. 2 holes × 2 = 4 holes when unfolded.",topic:"Paper Folding"},
  {id:88,question:"Complete: ACEG, BDFH, CEGI, ?",options:{A:"DFHJ",B:"DEGH",C:"DFHI",D:"DEGJ"},correct:"A",explanation:"Each set starts one letter higher: A,B,C,D. Pattern +2 within: D,F,H,J.",topic:"Letter Series"},
  {id:89,question:"Dice: If 1 opposite 6, 2 opposite 5, what's opposite 3?",options:{A:"1",B:"2",C:"4",D:"5"},correct:"C",explanation:"Standard dice: 1↔6, 2↔5, 3↔4.",topic:"Dice"},
  {id:90,question:"A is 2 years older than B. B is 3 years older than C. C is 25. A's age?",options:{A:"28",B:"29",C:"30",D:"31"},correct:"C",explanation:"C=25, B=28, A=30.",topic:"Blood Relations"},
  {id:91,question:"Series: 2, 5, 10, 17, 26, ?",options:{A:"35",B:"36",C:"37",D:"38"},correct:"C",explanation:"Differences: 3,5,7,9,11. Next=26+11=37. (Pattern: n²+1)",topic:"Number Series"},
  {id:92,question:"Analogy: Mercury : Planet :: Moon : ?",options:{A:"Star",B:"Satellite",C:"Planet",D:"Comet"},correct:"B",explanation:"Mercury is a planet. Moon is a satellite.",topic:"Analogy"},
  {id:93,question:"Statement: All cars are buses. Some buses are trains. I: Some cars are trains. II: Some trains are buses.",options:{A:"Only I",B:"Only II",C:"Both",D:"Neither"},correct:"B",explanation:"All cars→buses, some buses→trains. Some trains are buses (II valid — converse of premise). I not definite.",topic:"Syllogism"},
  {id:94,question:"If today is Friday, what was the day 100 days ago?",options:{A:"Monday",B:"Tuesday",C:"Wednesday",D:"Thursday"},correct:"C",explanation:"100/7=14 weeks+2 days. Friday-2=Wednesday.",topic:"Calendar"},
  {id:95,question:"Odd: Inch, Centimeter, Kilogram, Meter",options:{A:"Inch",B:"Centimeter",C:"Kilogram",D:"Meter"},correct:"C",explanation:"Kilogram measures weight. Others measure length.",topic:"Classification"},
  {id:96,question:"Water image of 'CHECK' (top-down flip):",options:{A:"Same",B:"Reversed vertically",C:"Only H,E,C change",D:"K changes"},correct:"B",explanation:"Water image = vertical flip (upside down mirror).",topic:"Mirror Image"},
  {id:97,question:"Series: 4, 7, 12, 19, 28, ?",options:{A:"37",B:"38",C:"39",D:"40"},correct:"C",explanation:"Differences: 3,5,7,9,11. Next=28+11=39.",topic:"Number Series"},
  {id:98,question:"A is father of C and D. B is mother of D. E is brother of A. E is ___ of D.",options:{A:"Uncle",B:"Father",C:"Grandfather",D:"Cousin"},correct:"A",explanation:"E is A's brother. D is A's child. E is D's uncle.",topic:"Blood Relations"},
  {id:99,question:"Analogy: Cow : Calf :: Horse : ?",options:{A:"Pony",B:"Foal",C:"Colt",D:"Lamb"},correct:"B",explanation:"Baby cow = calf. Baby horse = foal.",topic:"Analogy"},
  {id:100,question:"Series: 0, 1, 1, 2, 3, 5, 8, 13, ?",options:{A:"18",B:"20",C:"21",D:"26"},correct:"C",explanation:"Fibonacci: each = sum of previous two. 8+13=21.",topic:"Number Series"},
];
